[package]
name = "kobo-lichess"
version = "1.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
kobo-json = { path = "../../crates/kobo-json" }
kobo-sdk = { path = "../../crates/kobo-sdk" }
shakmaty = "=0.27.3"

[dev-dependencies]
kobo-profile = { path = "../../crates/kobo-profile" }
kobo-ui = { path = "../../crates/kobo-ui" }

[lints]
workspace = true
