[package]
name = "kobo-bookview"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
kobo-doc = { path = "../kobo-doc" }
kobo-image = { path = "../kobo-image" }
kobo-read = { path = "../kobo-read" }
kobo-sdk = { path = "../kobo-sdk" }
kobo-ui = { path = "../kobo-ui" }

[lints]
workspace = true
