[package]
name = "kobo-bookview"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
kobo-net = { path = "../kobo-net" }
kobo-comic = { path = "../kobo-comic" }
kobo-doc = { path = "../kobo-doc" }
kobo-image = { path = "../kobo-image" }
kobo-json = { path = "../kobo-json" }
kobo-read = { path = "../kobo-read" }
kobo-sdk = { path = "../kobo-sdk" }
kobo-ui = { path = "../kobo-ui" }

[lints]
workspace = true

[dev-dependencies]
kobo-profile = { path = "../kobo-profile" }
kobo-text = { path = "../kobo-text" }
