[package]
name = "kobo-gutenbird"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
kobo-bookview = { path = "../../crates/kobo-bookview" }
kobo-doc = { path = "../../crates/kobo-doc" }
kobo-image = { path = "../../crates/kobo-image" }
kobo-opds = { path = "../../crates/kobo-opds" }
kobo-read = { path = "../../crates/kobo-read" }
kobo-sdk = { path = "../../crates/kobo-sdk" }

[dev-dependencies]
kobo-ui = { path = "../../crates/kobo-ui" }

[lints]
workspace = true
