[package]
name = "kobo-gutenbird"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
kobo-bookview = { path = "../../crates/kobo-bookview" }
kobo-doc = { path = "../../crates/kobo-doc", features = ["raster"] }
kobo-image = { path = "../../crates/kobo-image" }
kobo-opds = { path = "../../crates/kobo-opds" }
kobo-read = { path = "../../crates/kobo-read", features = ["raster"] }
kobo-sdk = { path = "../../crates/kobo-sdk" }

[dev-dependencies]
kobo-profile = { path = "../../crates/kobo-profile" }
kobo-ui = { path = "../../crates/kobo-ui" }

[lints]
workspace = true
