[package]
name = "kobo-zotero-reader"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
kobo-bookview = { path = "../../crates/kobo-bookview", features = ["raster"] }
kobo-doc = { path = "../../crates/kobo-doc" }
kobo-json = { path = "../../crates/kobo-json" }
kobo-read = { path = "../../crates/kobo-read" }
kobo-sdk = { path = "../../crates/kobo-sdk" }

[lints]
workspace = true
