[package]
name = "kobo-shell"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kobo-abi = { path = "../kobo-abi", default-features = false }
kobo-policy = { path = "../kobo-policy" }
kobo-protocol = { path = "../kobo-protocol" }

[lints]
workspace = true
