[package]
name = "kobo-rss"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
kobo-html = { path = "../../crates/kobo-html" }
kobo-json = { path = "../../crates/kobo-json" }
kobo-sdk = { path = "../../crates/kobo-sdk" }
kobo-xml = { path = "../../crates/kobo-xml" }

[dev-dependencies]
kobo-ui = { path = "../../crates/kobo-ui" }

[lints]
workspace = true
