[package]
name = "kobo-logicpack"
version = "0.1.3"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
kobo-sdk = { path = "../../crates/kobo-sdk" }

kobo-state = { path = "../../crates/kobo-state" }
kobo-json = { path = "../../crates/kobo-json" }

[dev-dependencies]
kobo-ui = { path = "../../crates/kobo-ui" }

[lints]
workspace = true
