//! Reading an EPUB as a document.
//!
//! # What an EPUB is
//!
//! A zip archive containing XHTML files, plus two pieces of paperwork saying
//! which files they are and what order to read them in:
//!
//! 1. `META-INF/container.xml`, at a fixed path, naming the package document.
//! 2. The package document (the OPF) holding the metadata, a *manifest* of
//!    every file with an identifier, and a *spine* of identifiers in reading
//!    order.
//!
//! So opening a book is: read the archive's table of contents, follow the
//! container to the package, follow the package's spine through its manifest
//! to the files, and run each one through the HTML parser. The blocks are
//! joined into one document with a [`Block::Break`] at each seam, because a
//! chapter of an EPUB is a file and the reader who asks for the next chapter
//! means the next file even when nobody wrote a heading at the top of it.
//!
//! # Tolerance
//!
//! Real EPUBs are generated by a dozen tools and hand-edited afterwards. The
//! spine points at identifiers that are not in the manifest; the manifest
//! points at files that are not in the archive; hrefs are percent-encoded, or
//! spelled with the wrong case, or relative to the wrong directory. Every one
//! of those is skipped past rather than refused, because the alternative is a
//! book that will not open on account of one broken link in its front matter.
//! Only a file with no readable text at all is refused.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use kobo_html::{attribute, decode_entities, element_name};

use crate::html::skip_bracketed;
use crate::zip::{self, Archive};
use crate::{Block, Builder, Document};

/// Where the container always is. The one path in an EPUB that is fixed.
const CONTAINER: &str = "META-INF/container.xml";

/// The most spine items that will be read.
///
/// A book is a few hundred files. This bounds the work done for an archive
/// whose spine names the same file fifty thousand times.
const MAX_PARTS: usize = 4_096;

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Fault {
    /// The bytes are not a usable zip archive.
    Archive(zip::Fault),
    /// A zip archive, but not one with a book in it.
    NotABook,
}

impl std::fmt::Display for Fault {
    fn fmt(&self, out: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Archive(fault) => fault.fmt(out),
            Self::NotABook => out.write_str("there is no book in this archive"),
        }
    }
}

impl std::error::Error for Fault {}

impl From<zip::Fault> for Fault {
    fn from(fault: zip::Fault) -> Self {
        Self::Archive(fault)
    }
}

/// Reads an EPUB.
///
/// # Errors
///
/// [`Fault::Archive`] when the bytes are not a readable zip, and
/// [`Fault::NotABook`] when they are but no readable text could be found.
pub fn parse(bytes: &[u8]) -> Result<Document, Fault> {
    let archive = Archive::open(bytes)?;
    let package_at = find_package(&archive).ok_or(Fault::NotABook)?;
    let package = read_package(&text_of(&archive.read(&package_at)?));
    let base = directory_of(&package_at);

    let mut builder = Builder::new();
    // The package's own metadata outranks anything found inside a chapter: the
    // `<title>` of chapter four is "Chapter Four".
    if let Some(title) = &package.title {
        builder.set_title(title);
    }
    if let Some(author) = &package.author {
        builder.set_author(author);
    }

    let mut truncated = false;
    let mut parts = 0;
    for id in package.reading_order() {
        if parts >= MAX_PARTS {
            truncated = true;
            break;
        }
        let Some(item) = package.manifest.get(id) else {
            // A spine entry naming nothing is a broken book, not a reason to
            // refuse the chapters that are fine.
            continue;
        };
        if !is_readable(&item.media_type, &item.href) {
            continue;
        }
        let Ok(bytes) = archive.read(&resolve(&base, &item.href)) else {
            continue;
        };
        let part = crate::html::parse(&text_of(&bytes));
        truncated |= part.truncated;
        if part.blocks.is_empty() {
            // An empty file (a cover page holding only an image) should not
            // leave a chapter break behind it with nothing on either side.
            continue;
        }
        if parts > 0 {
            builder.push(Block::Break);
        }
        for block in part.blocks {
            builder.push(block);
        }
        parts += 1;
    }

    if parts == 0 {
        return Err(Fault::NotABook);
    }
    let mut document = builder.finish();
    document.truncated |= truncated;
    Ok(document)
}

/// Finds the package document.
///
/// The container names it. When the container is missing or says nothing
/// usable (which happens, because it is the one file every tool assumes
/// somebody else wrote) the archive is searched for the one file that ends in
/// `.opf`, which is what a person would do.
// `Path::extension` is what the lint suggests, and it is wrong here: these are
// zip member names, not paths on this machine, and on Windows `Path` would take
// a backslash for a separator when a zip's separator is always a slash. The
// names have already been lower-cased where it matters.
#[allow(clippy::case_sensitive_file_extension_comparisons)]
fn find_package(archive: &Archive<'_>) -> Option<String> {
    if let Ok(container) = archive.read(CONTAINER) {
        if let Some(path) = root_file(&text_of(&container)) {
            return Some(path);
        }
    }
    archive
        .names()
        .find(|name| name.ends_with(".opf"))
        .map(str::to_owned)
}

/// The path the container points at.
fn root_file(xml: &str) -> Option<String> {
    let mut found = None;
    for_each_element(xml, |name, inside, closing, _| {
        if !closing && name == "rootfile" && found.is_none() {
            found = attribute(inside, "full-path")
                .map(decode_entities)
                .filter(|path| !path.trim().is_empty());
        }
    });
    found
}

/// One file listed in the package's manifest.
struct Item {
    href: String,
    media_type: String,
}

/// What the package document says.
struct Package {
    title: Option<String>,
    author: Option<String>,
    manifest: BTreeMap<String, Item>,
    /// Spine entries in order, each with whether it is part of the main flow.
    spine: Vec<(String, bool)>,
}

impl Package {
    /// The identifiers to read, in order.
    ///
    /// Entries marked `linear="no"` are outside the reading flow (a cover
    /// page, a set of endnotes reached by a link) and are left out. But a
    /// book whose *every* entry is marked that way is a book somebody's tool
    /// mislabelled, and honouring the marking there yields nothing at all, so
    /// in that case the marking is ignored and the whole spine is read.
    fn reading_order(&self) -> impl Iterator<Item = &String> {
        let any_linear = self.spine.iter().any(|(_, linear)| *linear);
        self.spine
            .iter()
            .filter(move |(_, linear)| *linear || !any_linear)
            .map(|(id, _)| id)
    }
}

/// Reads the package document.
fn read_package(xml: &str) -> Package {
    let mut package = Package {
        title: None,
        author: None,
        manifest: BTreeMap::new(),
        spine: Vec::new(),
    };
    // The same element names appear in more than one place (`<title>` is in
    // the metadata and also in a `<guide>` reference) so the section matters.
    let mut in_metadata = false;
    for_each_element(xml, |name, inside, closing, before| {
        // A namespace prefix is chosen by whoever wrote the file. `dc:title`
        // and a `title` under a default Dublin Core namespace are the same
        // element, and the prefix is not worth resolving properly for the two
        // fields being read.
        let local = name.rsplit(':').next().unwrap_or(name);
        match (closing, local) {
            (false, "metadata") => in_metadata = true,
            (true, "metadata") => in_metadata = false,
            (true, "title") if in_metadata && package.title.is_none() => {
                package.title = Some(decode_entities(before));
            }
            (true, "creator") if in_metadata && package.author.is_none() => {
                package.author = Some(decode_entities(before));
            }
            (false, "item") => {
                let id = attribute(inside, "id").map(decode_entities);
                let href = attribute(inside, "href").map(decode_entities);
                if let (Some(id), Some(href)) = (id, href) {
                    package.manifest.insert(
                        id,
                        Item {
                            href,
                            media_type: attribute(inside, "media-type")
                                .unwrap_or_default()
                                .to_ascii_lowercase(),
                        },
                    );
                }
            }
            (false, "itemref") => {
                if let Some(id) = attribute(inside, "idref").map(decode_entities) {
                    let linear = attribute(inside, "linear")
                        .is_none_or(|value| !value.eq_ignore_ascii_case("no"));
                    package.spine.push((id, linear));
                }
            }
            _ => {}
        }
    });
    package
}

/// Whether a manifest entry is something with words in it.
///
/// The media type is checked first because it is what the specification says
/// to use, and the extension second because a manifest with no media types in
/// it is a thing that exists.
#[allow(clippy::case_sensitive_file_extension_comparisons)]
fn is_readable(media_type: &str, href: &str) -> bool {
    if !media_type.is_empty() {
        return media_type.contains("xhtml") || media_type.contains("text/html");
    }
    let path = href.split(['#', '?']).next().unwrap_or(href);
    let lower = path.to_ascii_lowercase();
    lower.ends_with(".xhtml") || lower.ends_with(".html") || lower.ends_with(".htm")
}

/// Walks the elements of an XML document.
///
/// A scan, not a parser: XML's well-formedness rules are not checked and its
/// namespaces are not resolved, because the only thing wanted here is a
/// handful of elements and their attributes. `before` is the text since the
/// previous tag, which is how an element's content is read.
fn for_each_element(xml: &str, mut visit: impl FnMut(&str, &str, bool, &str)) {
    let mut rest = xml;
    while let Some(at) = rest.find('<') {
        let before = &rest[..at];
        let tail = &rest[at..];
        if let Some(after) = skip_bracketed(tail) {
            rest = after;
            continue;
        }
        let Some(end) = tail.find('>') else {
            return;
        };
        let inside = &tail[1..end];
        rest = &tail[end + 1..];
        // A processing instruction (`<?xml … ?>`) is not an element.
        if inside.starts_with('?') || inside.starts_with('!') {
            continue;
        }
        let name = element_name(inside);
        visit(&name, inside, inside.starts_with('/'), before);
        // A tag that closes itself both opens and closes. Without this, the
        // text after `<title/>` would be read as the title's content.
        if inside.ends_with('/') && !inside.starts_with('/') {
            visit(&name, inside, true, "");
        }
    }
}

/// The directory part of a path, with its trailing separator.
fn directory_of(path: &str) -> String {
    match path.rfind('/') {
        Some(at) => path[..=at].to_owned(),
        None => String::new(),
    }
}

/// Turns an href from the package into a path into the archive.
///
/// Three things happen: the fragment goes, because `chapter1.xhtml#part2` is a
/// place inside a file rather than a different file; percent escapes are
/// undone, because a filename with a space in it is written `%20` in an href
/// and stored with a space in the archive; and `..` is resolved, because a
/// package in `OEBPS/` referring to `../images/a.png` means the archive root.
fn resolve(base: &str, href: &str) -> String {
    let path = href.split(['#', '?']).next().unwrap_or(href);
    let path = unescape(path);
    let joined = if path.starts_with('/') {
        path.trim_start_matches('/').to_owned()
    } else {
        format!("{base}{path}")
    };
    let mut parts: Vec<&str> = Vec::new();
    for part in joined.split('/') {
        match part {
            "" | "." => {}
            ".." => {
                parts.pop();
            }
            other => parts.push(other),
        }
    }
    parts.join("/")
}

/// Undoes percent escapes, leaving anything that is not one alone.
fn unescape(path: &str) -> String {
    if !path.contains('%') {
        return path.to_owned();
    }
    let mut out: Vec<u8> = Vec::with_capacity(path.len());
    let bytes = path.as_bytes();
    let mut at = 0;
    while at < bytes.len() {
        // A `%` that is not followed by two hex digits is a literal `%`, which
        // is a character a filename is allowed to contain.
        if bytes[at] == b'%' && at + 2 < bytes.len() {
            let hex = &path[at + 1..at + 3];
            if let Ok(byte) = u8::from_str_radix(hex, 16) {
                out.push(byte);
                at += 3;
                continue;
            }
        }
        out.push(bytes[at]);
        at += 1;
    }
    String::from_utf8_lossy(&out).into_owned()
}

/// Reads a member's bytes as text.
///
/// EPUB allows UTF-8 and UTF-16. UTF-16 is vanishingly rare and completely
/// unreadable if guessed wrong (every character of the book comes out as a
/// pair of wrong ones) so the byte-order mark is honoured where there is one.
fn text_of(bytes: &[u8]) -> String {
    if let Some(body) = bytes.strip_prefix(&[0xef, 0xbb, 0xbf]) {
        return String::from_utf8_lossy(body).into_owned();
    }
    for (mark, big_endian) in [([0xfe_u8, 0xff_u8], true), ([0xff, 0xfe], false)] {
        if let Some(body) = bytes.strip_prefix(&mark[..]) {
            let units: Vec<u16> = body
                .chunks_exact(2)
                .map(|pair| {
                    if big_endian {
                        u16::from_be_bytes([pair[0], pair[1]])
                    } else {
                        u16::from_le_bytes([pair[0], pair[1]])
                    }
                })
                .collect();
            return String::from_utf16_lossy(&units);
        }
    }
    String::from_utf8_lossy(bytes).into_owned()
}

/// One chapter to write, as a title and its prose.
///
/// The body is plain text in which a blank line starts a new paragraph, which
/// is how prose arrives from a person typing and from a language model, and
/// spares every caller from having to hand-write XHTML.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Chapter {
    pub title: String,
    pub body: String,
}

/// Writes an EPUB.
///
/// The layout is deliberately the plainest one that is still a real EPUB:
/// EPUB 2 with an NCX, because that is what the widest range of readers will
/// open, including the firmware's own. A generated book has no cover image, no
/// stylesheet and no scripts, and inventing them would only add files that
/// could be wrong.
///
/// Two details of the container format are not optional and are easy to get
/// wrong. `mimetype` must be the archive's first member and must be stored
/// rather than deflated, which is why it is pushed first and why
/// [`zip::stored`] is the right writer: it stores every member and preserves
/// the order it is given.
///
/// The identifier is derived from the title rather than randomly generated, so
/// that writing the same book twice produces the same bytes. A reproducible
/// output is worth more here than a globally unique one, and no random source
/// is available to this crate anyway.
///
/// # Errors
///
/// Returns [`zip::Fault`] when the archive cannot be represented, which for a
/// book of text means it is far past four gigabytes.
pub fn write(
    title: &str,
    author: Option<&str>,
    chapters: &[Chapter],
) -> Result<Vec<u8>, zip::Fault> {
    let identifier = format!("urn:cobalt:{}", slug(title));
    let mut manifest = String::new();
    let mut spine = String::new();
    let mut nav = String::new();
    let mut files: Vec<(String, Vec<u8>)> = Vec::with_capacity(chapters.len());
    for (index, chapter) in chapters.iter().enumerate() {
        let id = format!("ch{}", index + 1);
        let href = format!("{id}.xhtml");
        let _ = writeln!(
            manifest,
            "    <item id=\"{id}\" href=\"{href}\" media-type=\"application/xhtml+xml\"/>"
        );
        let _ = writeln!(spine, "    <itemref idref=\"{id}\"/>");
        let _ = write!(
            nav,
            "    <navPoint id=\"nav-{id}\" playOrder=\"{}\">\n      \
             <navLabel><text>{}</text></navLabel>\n      \
             <content src=\"{href}\"/>\n    </navPoint>\n",
            index + 1,
            escape(&chapter.title),
        );
        files.push((
            format!("OEBPS/{href}"),
            chapter_xhtml(&chapter.title, &chapter.body).into_bytes(),
        ));
    }

    // mimetype first, and stored, or it is not an EPUB whatever else is right.
    let mut members = vec![
        ("mimetype".to_owned(), b"application/epub+zip".to_vec()),
        (CONTAINER.to_owned(), container_xml().into_bytes()),
        (
            "OEBPS/content.opf".to_owned(),
            package_opf(title, author, &identifier, &manifest, &spine).into_bytes(),
        ),
        (
            "OEBPS/toc.ncx".to_owned(),
            toc_ncx(title, &identifier, &nav).into_bytes(),
        ),
    ];
    members.append(&mut files);
    zip::stored(&members)
}

fn container_xml() -> String {
    String::from(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <container version=\"1.0\" \
         xmlns=\"urn:oasis:names:tc:opendocument:xmlns:container\">\n  \
         <rootfiles>\n    \
         <rootfile full-path=\"OEBPS/content.opf\" \
         media-type=\"application/oebps-package+xml\"/>\n  \
         </rootfiles>\n</container>\n"
    )
}

fn package_opf(
    title: &str,
    author: Option<&str>,
    identifier: &str,
    manifest: &str,
    spine: &str,
) -> String {
    let creator = author.map_or_else(String::new, |author| {
        format!(
            "    <dc:creator opf:role=\"aut\">{}</dc:creator>\n",
            escape(author)
        )
    });
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <package xmlns=\"http://www.idpf.org/2007/opf\" version=\"2.0\" \
         unique-identifier=\"bookid\">\n  \
         <metadata xmlns:dc=\"http://purl.org/dc/elements/1.1/\" \
         xmlns:opf=\"http://www.idpf.org/2007/opf\">\n    \
         <dc:title>{}</dc:title>\n{creator}    \
         <dc:language>en</dc:language>\n    \
         <dc:identifier id=\"bookid\">{}</dc:identifier>\n  \
         </metadata>\n  <manifest>\n    \
         <item id=\"ncx\" href=\"toc.ncx\" media-type=\"application/x-dtbncx+xml\"/>\n\
         {manifest}  </manifest>\n  <spine toc=\"ncx\">\n{spine}  </spine>\n</package>\n",
        escape(title),
        escape(identifier),
    )
}

fn toc_ncx(title: &str, identifier: &str, nav: &str) -> String {
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <ncx xmlns=\"http://www.daisy.org/z3986/2005/ncx/\" version=\"2005-1\">\n  \
         <head>\n    <meta name=\"dtb:uid\" content=\"{}\"/>\n    \
         <meta name=\"dtb:depth\" content=\"1\"/>\n    \
         <meta name=\"dtb:totalPageCount\" content=\"0\"/>\n    \
         <meta name=\"dtb:maxPageNumber\" content=\"0\"/>\n  </head>\n  \
         <docTitle><text>{}</text></docTitle>\n  <navMap>\n{nav}  </navMap>\n</ncx>\n",
        escape(identifier),
        escape(title),
    )
}

fn chapter_xhtml(title: &str, body: &str) -> String {
    let mut prose = String::new();
    for paragraph in paragraphs(body) {
        let _ = writeln!(prose, "<p>{}</p>", escape(&paragraph));
    }
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <!DOCTYPE html>\n\
         <html xmlns=\"http://www.w3.org/1999/xhtml\">\n\
         <head><title>{0}</title></head>\n\
         <body>\n<h1>{0}</h1>\n{prose}</body>\n</html>\n",
        escape(title),
    )
}

/// Splits prose into paragraphs on blank lines.
fn paragraphs(body: &str) -> Vec<String> {
    let normalised = crate::normalise_breaks(body);
    let mut out = Vec::new();
    let mut current = String::new();
    for line in normalised.split('\n') {
        if line.trim().is_empty() {
            if !current.trim().is_empty() {
                out.push(current.trim().to_owned());
            }
            current.clear();
        } else {
            if !current.is_empty() {
                current.push(' ');
            }
            current.push_str(line.trim());
        }
    }
    if !current.trim().is_empty() {
        out.push(current.trim().to_owned());
    }
    out
}

/// Escapes text for use in XML content or in a double-quoted attribute.
///
/// All five characters are escaped regardless of position so that one function
/// is safe in both places. Control characters that XML forbids outright are
/// dropped rather than escaped, because there is no spelling of them that a
/// conforming parser will accept.
fn escape(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for character in text.chars() {
        match character {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            '\t' | '\n' => out.push(character),
            control if control < ' ' || control == '\u{7f}' => {}
            other => out.push(other),
        }
    }
    out
}

/// A lowercase identifier safe to put in a URN.
fn slug(title: &str) -> String {
    let mut out = String::new();
    for character in title.chars() {
        if character.is_ascii_alphanumeric() {
            out.extend(character.to_lowercase());
        } else if !out.ends_with('-') && !out.is_empty() {
            out.push('-');
        }
    }
    let trimmed = out.trim_end_matches('-');
    if trimmed.is_empty() {
        "book".to_owned()
    } else {
        trimmed.to_owned()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::zip::tests::archive;

    const CONTAINER_XML: &str = r#"<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/book.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>"#;

    fn opf(spine: &str, manifest: &str) -> String {
        format!(
            r#"<?xml version="1.0"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:title>A Book</dc:title>
    <dc:creator>A Person</dc:creator>
  </metadata>
  <manifest>{manifest}</manifest>
  <spine>{spine}</spine>
</package>"#
        )
    }

    fn a_book() -> Vec<u8> {
        let package = opf(
            r#"<itemref idref="one"/><itemref idref="two"/>"#,
            r#"<item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>
               <item id="two" href="two.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        archive(&[
            ("mimetype", b"application/epub+zip"),
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            (
                "OEBPS/one.xhtml",
                b"<html><body><h1>Chapter One</h1><p>It began badly.</p></body></html>",
            ),
            (
                "OEBPS/two.xhtml",
                b"<html><body><h1>Chapter Two</h1><p>It got worse.</p></body></html>",
            ),
        ])
    }

    #[test]
    fn a_book_comes_back_in_its_reading_order() {
        let document = parse(&a_book()).expect("a readable book");
        let words: Vec<&str> = document
            .blocks
            .iter()
            .filter_map(|block| block.text())
            .collect();
        assert_eq!(
            words,
            vec![
                "Chapter One",
                "It began badly.",
                "Chapter Two",
                "It got worse."
            ]
        );
    }

    #[test]
    fn the_package_says_what_the_book_is_and_the_chapters_do_not_overrule_it() {
        let document = parse(&a_book()).expect("a readable book");
        assert_eq!(document.title.as_deref(), Some("A Book"));
        assert_eq!(document.author.as_deref(), Some("A Person"));
    }

    #[test]
    fn each_file_is_a_part_that_can_be_navigated_to() {
        let document = parse(&a_book()).expect("a readable book");
        assert_eq!(document.parts().len(), 2, "{:?}", document.blocks);
        assert_eq!(document.part_title(0), Some("Chapter One"));
    }

    #[test]
    fn the_spine_and_not_the_archive_decides_the_order() {
        // The archive is sorted by name, so a book whose chapters are `a`, `b`
        // and `c` reads correctly by accident. This one does not.
        let package = opf(
            r#"<itemref idref="second"/><itemref idref="first"/>"#,
            r#"<item id="first" href="a.xhtml" media-type="application/xhtml+xml"/>
               <item id="second" href="z.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/a.xhtml", b"<p>Last.</p>"),
            ("OEBPS/z.xhtml", b"<p>First.</p>"),
        ]);
        let document = parse(&bytes).expect("a readable book");
        let words: Vec<&str> = document
            .blocks
            .iter()
            .filter_map(|block| block.text())
            .collect();
        assert_eq!(words, vec!["First.", "Last."]);
    }

    #[test]
    fn an_href_with_an_escape_in_it_still_finds_its_file() {
        let package = opf(
            r#"<itemref idref="one"/>"#,
            r#"<item id="one" href="my%20chapter.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/my chapter.xhtml", b"<p>Found.</p>"),
        ]);
        let document = parse(&bytes).expect("a readable book");
        assert_eq!(document.blocks[0].text(), Some("Found."));
    }

    #[test]
    fn an_href_that_climbs_out_of_the_package_directory_is_followed() {
        let package = opf(
            r#"<itemref idref="one"/>"#,
            r#"<item id="one" href="../text/one.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("text/one.xhtml", b"<p>Found.</p>"),
        ]);
        let document = parse(&bytes).expect("a readable book");
        assert_eq!(document.blocks[0].text(), Some("Found."));
    }

    #[test]
    fn a_fragment_is_a_place_in_a_file_and_not_a_different_file() {
        let package = opf(
            r#"<itemref idref="one"/>"#,
            r#"<item id="one" href="one.xhtml#part2" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/one.xhtml", b"<p>Found.</p>"),
        ]);
        assert_eq!(
            parse(&bytes).expect("a readable book").blocks[0].text(),
            Some("Found.")
        );
    }

    #[test]
    fn a_broken_link_costs_one_chapter_and_not_the_book() {
        let package = opf(
            r#"<itemref idref="missing"/><itemref idref="gone"/><itemref idref="one"/>"#,
            r#"<item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>
               <item id="gone" href="nowhere.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/one.xhtml", b"<p>Still here.</p>"),
        ]);
        let document = parse(&bytes).expect("a readable book");
        assert_eq!(document.blocks[0].text(), Some("Still here."));
    }

    #[test]
    fn a_picture_in_the_manifest_is_not_read_as_prose() {
        let package = opf(
            r#"<itemref idref="art"/><itemref idref="one"/>"#,
            r#"<item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>
               <item id="art" href="cover.png" media-type="image/png"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/one.xhtml", b"<p>Words.</p>"),
            ("OEBPS/cover.png", &[0x89, b'P', b'N', b'G']),
        ]);
        let document = parse(&bytes).expect("a readable book");
        assert_eq!(document.blocks, vec![Block::Paragraph("Words.".to_owned())]);
    }

    #[test]
    fn a_missing_container_is_worked_around_rather_than_refused() {
        // The one file every tool assumes somebody else wrote.
        let package = opf(
            r#"<itemref idref="one"/>"#,
            r#"<item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/one.xhtml", b"<p>Found anyway.</p>"),
        ]);
        assert_eq!(
            parse(&bytes).expect("a readable book").blocks[0].text(),
            Some("Found anyway.")
        );
    }

    #[test]
    fn a_book_whose_every_part_is_marked_ancillary_is_still_read() {
        // Honouring the marking here would leave nothing at all, and a book
        // that opens empty is worse than one that shows its cover page.
        let package = opf(
            r#"<itemref idref="one" linear="no"/>"#,
            r#"<item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/one.xhtml", b"<p>Everything.</p>"),
        ]);
        assert_eq!(
            parse(&bytes).expect("a readable book").blocks[0].text(),
            Some("Everything.")
        );
    }

    #[test]
    fn an_ancillary_part_is_left_out_when_there_is_a_flow_without_it() {
        let package = opf(
            r#"<itemref idref="cover" linear="no"/><itemref idref="one"/>"#,
            r#"<item id="cover" href="cover.xhtml" media-type="application/xhtml+xml"/>
               <item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/cover.xhtml", b"<p>A cover.</p>"),
            ("OEBPS/one.xhtml", b"<p>The book.</p>"),
        ]);
        let document = parse(&bytes).expect("a readable book");
        assert_eq!(
            document.blocks,
            vec![Block::Paragraph("The book.".to_owned())]
        );
    }

    #[test]
    fn an_empty_file_does_not_leave_a_chapter_break_behind_it() {
        let package = opf(
            r#"<itemref idref="blank"/><itemref idref="one"/>"#,
            r#"<item id="blank" href="blank.xhtml" media-type="application/xhtml+xml"/>
               <item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/blank.xhtml", b"<html><body></body></html>"),
            ("OEBPS/one.xhtml", b"<p>The book.</p>"),
        ]);
        let document = parse(&bytes).expect("a readable book");
        assert_eq!(
            document.blocks,
            vec![Block::Paragraph("The book.".to_owned())]
        );
    }

    #[test]
    fn a_file_in_utf_sixteen_is_not_read_as_mojibake() {
        let package = opf(
            r#"<itemref idref="one"/>"#,
            r#"<item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let mut wide: Vec<u8> = vec![0xff, 0xfe];
        for unit in "<p>Readable.</p>".encode_utf16() {
            wide.extend_from_slice(&unit.to_le_bytes());
        }
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/one.xhtml", &wide),
        ]);
        assert_eq!(
            parse(&bytes).expect("a readable book").blocks[0].text(),
            Some("Readable.")
        );
    }

    #[test]
    fn something_that_is_not_a_book_is_refused_and_says_which_way() {
        assert_eq!(
            parse(b"not a zip"),
            Err(Fault::Archive(zip::Fault::NotAnArchive))
        );
        let empty = archive(&[("readme.txt", b"nothing to read here")]);
        assert_eq!(parse(&empty), Err(Fault::NotABook));
    }

    #[test]
    fn a_self_closing_tag_does_not_swallow_what_follows_it() {
        assert_eq!(root_file(CONTAINER_XML).as_deref(), Some("OEBPS/book.opf"));
        let package = read_package(&opf("", ""));
        assert_eq!(package.title.as_deref(), Some("A Book"));
    }

    #[test]
    fn paths_are_resolved_the_way_a_browser_would() {
        assert_eq!(resolve("OEBPS/", "one.xhtml"), "OEBPS/one.xhtml");
        assert_eq!(resolve("OEBPS/", "../text/one.xhtml"), "text/one.xhtml");
        assert_eq!(resolve("OEBPS/", "./one.xhtml"), "OEBPS/one.xhtml");
        assert_eq!(resolve("OEBPS/", "/one.xhtml"), "one.xhtml");
        assert_eq!(resolve("", "one.xhtml"), "one.xhtml");
        assert_eq!(resolve("a/b/", "../../c.xhtml"), "c.xhtml");
        // Climbing past the root cannot reach outside the archive.
        assert_eq!(resolve("a/", "../../../c.xhtml"), "c.xhtml");
    }

    #[test]
    fn an_escape_that_is_not_one_is_left_alone() {
        assert_eq!(unescape("100%"), "100%");
        assert_eq!(unescape("a%zzb"), "a%zzb");
        assert_eq!(unescape("a%20b"), "a b");
    }

    #[test]
    fn nothing_here_panics_on_anything() {
        let good = a_book();
        for cut in (0..good.len()).step_by(7) {
            let _ = parse(&good[..cut]);
        }
        for at in (0..good.len()).step_by(11) {
            let mut bytes = good.clone();
            bytes[at] ^= 0xff;
            let _ = parse(&bytes);
        }
        for xml in ["", "<", "<?xml", "<rootfile", "<metadata><title>"] {
            let _ = root_file(xml);
            let _ = read_package(xml);
        }
    }

    fn chapters() -> Vec<Chapter> {
        vec![
            Chapter {
                title: "The Sea & the Sky".to_owned(),
                body: "First paragraph.\n\nSecond <paragraph>.".to_owned(),
            },
            Chapter {
                title: "Tides".to_owned(),
                body: "Only one here.".to_owned(),
            },
        ]
    }

    /// The whole point of the writer: what it produces, the parser beside it
    /// must be able to read. A writer verified only against its own expected
    /// bytes can be confidently, consistently wrong.
    #[test]
    fn a_written_book_reads_back_as_the_same_book() {
        let bytes = write("A History of the Moon", Some("Cobalt Audio"), &chapters())
            .expect("a small book fits a zip");
        let document = parse(&bytes).expect("what we wrote must parse");

        assert_eq!(document.title.as_deref(), Some("A History of the Moon"));
        assert_eq!(document.author.as_deref(), Some("Cobalt Audio"));

        // Both chapter titles survive as headings that "next chapter" can find.
        let titles: Vec<&str> = document
            .parts()
            .iter()
            .filter_map(|start| document.part_title(*start))
            .collect();
        assert_eq!(titles, ["The Sea & the Sky", "Tides"]);

        // And the prose, with the markup-looking text intact rather than eaten.
        let prose: Vec<&str> = document
            .blocks
            .iter()
            .filter_map(|block| match block {
                Block::Paragraph(text) => Some(text.as_str()),
                _ => None,
            })
            .collect();
        assert_eq!(
            prose,
            ["First paragraph.", "Second <paragraph>.", "Only one here."]
        );
    }

    /// Sniffing decides which parser runs, so a written book must be
    /// recognisable as an EPUB from its bytes and not only from its name.
    #[test]
    fn a_written_book_is_recognised_as_an_epub() {
        let bytes = write("Book", None, &chapters()).expect("a small book fits a zip");
        assert_eq!(crate::sniff("book.epub", &bytes), crate::Format::Epub);
        assert_eq!(crate::sniff("unnamed", &bytes), crate::Format::Epub);
        assert!(crate::read("book.epub", &bytes).is_ok());
    }

    /// `mimetype` must be the first member and stored uncompressed. Readers
    /// that check this refuse the file outright, and the check is invisible in
    /// any test that only round-trips through our own parser.
    #[test]
    fn the_mimetype_is_first_and_stored() {
        let bytes = write("Book", None, &chapters()).expect("a small book fits a zip");
        assert!(
            bytes[30..].starts_with(b"mimetypeapplication/epub+zip"),
            "mimetype must be the first member, named and stored with no extras"
        );
        // Offset 8 of a local header is the compression method. 0 is stored.
        assert_eq!(u16::from_le_bytes([bytes[8], bytes[9]]), 0);
        let archive = Archive::open(&bytes).expect("a readable archive");
        assert_eq!(
            archive.read("mimetype").as_deref(),
            Ok(&b"application/epub+zip"[..])
        );
    }

    /// A book with no author must not claim one, and must still parse.
    #[test]
    fn an_author_is_left_out_rather_than_left_empty() {
        let bytes = write("Book", None, &chapters()).expect("a small book fits a zip");
        let document = parse(&bytes).expect("what we wrote must parse");
        assert_eq!(document.author, None);
    }

    #[test]
    fn a_title_that_is_all_punctuation_still_gets_an_identifier() {
        assert_eq!(slug("Moon: Past & Future"), "moon-past-future");
        assert_eq!(slug("???"), "book");
        assert_eq!(slug(""), "book");
    }

    /// Prose arrives as plain text, so blank lines are the only paragraph
    /// mark there is, and a single newline inside a paragraph is a wrap.
    #[test]
    fn blank_lines_separate_paragraphs_and_single_ones_do_not() {
        assert_eq!(
            paragraphs("one\nstill one\r\n\r\ntwo\n\n\n\nthree\n"),
            ["one still one", "two", "three"]
        );
        assert!(paragraphs("   \n\n  ").is_empty());
    }
}
