//! Reading an EPUB as a document.
//!
//! # What an EPUB is
//!
//! A zip archive containing XHTML files, plus two pieces of paperwork saying
//! which files they are and what order to read them in:
//!
//! 1. `META-INF/container.xml`, at a fixed path, naming the package document.
//! 2. The package document (the OPF) holding the metadata, a *manifest* of
//!    every file with an identifier, and a *spine* of identifiers in reading
//!    order.
//!
//! So opening a book is: read the archive's table of contents, follow the
//! container to the package, follow the package's spine through its manifest
//! to the files, and run each one through the HTML parser. The blocks are
//! joined into one document with a [`Block::Break`] at each seam, because a
//! chapter of an EPUB is a file and the reader who asks for the next chapter
//! means the next file even when nobody wrote a heading at the top of it.
//!
//! # Tolerance
//!
//! Real EPUBs are generated by a dozen tools and hand-edited afterwards. The
//! spine points at identifiers that are not in the manifest; the manifest
//! points at files that are not in the archive; hrefs are percent-encoded, or
//! spelled with the wrong case, or relative to the wrong directory. Every one
//! of those is skipped past rather than refused, because the alternative is a
//! book that will not open on account of one broken link in its front matter.
//! Only a file with no readable text at all is refused.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use kobo_html::{attribute, decode_entities, element_name, skip_element};

use crate::html::skip_bracketed;
use crate::zip::{self, Archive};
use crate::{collapse, Block, Builder, Contents, Document};

/// Where the container always is. The one path in an EPUB that is fixed.
const CONTAINER: &str = "META-INF/container.xml";

/// The most spine items that will be read.
///
/// A book is a few hundred files. This bounds the work done for an archive
/// whose spine names the same file fifty thousand times.
const MAX_PARTS: usize = 4_096;

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Fault {
    /// The bytes are not a usable zip archive.
    Archive(zip::Fault),
    /// A zip archive, but not one with a book in it.
    NotABook,
}

impl std::fmt::Display for Fault {
    fn fmt(&self, out: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Archive(fault) => fault.fmt(out),
            Self::NotABook => out.write_str("there is no book in this archive"),
        }
    }
}

impl std::error::Error for Fault {}

impl From<zip::Fault> for Fault {
    fn from(fault: zip::Fault) -> Self {
        Self::Archive(fault)
    }
}

/// Reads an EPUB.
///
/// # Errors
///
/// [`Fault::Archive`] when the bytes are not a readable zip, and
/// [`Fault::NotABook`] when they are but no readable text could be found.
pub fn parse(bytes: &[u8]) -> Result<Document, Fault> {
    let archive = Archive::open(bytes)?;
    let package_at = find_package(&archive).ok_or(Fault::NotABook)?;
    let package = read_package(&text_of(&archive.read(&package_at)?));
    let base = directory_of(&package_at);

    let mut builder = Builder::new();
    // The package's own metadata outranks anything found inside a chapter: the
    // `<title>` of chapter four is "Chapter Four".
    if let Some(title) = &package.title {
        builder.set_title(title);
    }
    if let Some(author) = &package.author {
        builder.set_author(author);
    }

    let mut truncated = false;
    let mut parts = 0;
    // Where each file of the book begins, so that a contents entry naming a
    // file can be turned into somewhere to go. Kept as the resolved archive
    // name, which is what a contents href resolves to as well, so the two can
    // be compared without either knowing how the other was spelled.
    let mut starts: Vec<(String, usize)> = Vec::new();
    let mut anchors: BTreeMap<String, usize> = BTreeMap::new();
    for id in package.reading_order() {
        if parts >= MAX_PARTS {
            truncated = true;
            break;
        }
        let Some(item) = package.manifest.get(id) else {
            // A spine entry naming nothing is a broken book, not a reason to
            // refuse the chapters that are fine.
            continue;
        };
        if !is_readable(&item.media_type, &item.href) {
            continue;
        }
        let name = resolve(&base, &item.href);
        let Ok(bytes) = archive.read(&name) else {
            continue;
        };
        let part = crate::html::parse(&strip_toc(&text_of(&bytes)));
        truncated |= part.truncated;
        if part.blocks.is_empty() {
            // An empty file (a cover page holding only an image) should not
            // leave a chapter break behind it with nothing on either side.
            continue;
        }
        if parts > 0 {
            builder.push(Block::Break);
        }
        // Recorded after the break rather than before it, so that going to a
        // chapter lands on its first words rather than on the seam in front
        // of them.
        let start = builder.len();
        // A picture's source was written relative to the file that referred to
        // it, so it is resolved here, where that file is known, and the block
        // is rewritten to name the archive member instead. A picture the
        // archive does not hold becomes its own description, which is what a
        // book with a broken link should read as.
        let mut part = part;
        let inside = directory_of(&name);
        for block in &mut part.blocks {
            if let Block::Picture { name: source, .. } = block {
                *source = resolve(&inside, source);
            }
        }
        // The names inside this file are only unique within it -- most books
        // number their sections from one in every chapter -- so each is keyed
        // by the file it was written in before it joins the book's own map.
        for (id, at) in part.anchors {
            anchors.insert(format!("{name}#{id}"), start + at);
        }
        starts.push((name, start));
        for block in part.blocks {
            builder.push(block);
        }
        parts += 1;
    }

    if parts == 0 {
        return Err(Fault::NotABook);
    }
    builder.set_contents(contents_of(&archive, &package, &base, &starts, &anchors));
    builder.set_anchors(anchors);
    builder.set_images(images_of(&archive, &builder));
    let mut document = builder.finish();
    document.truncated |= truncated;
    Ok(document)
}

/// The most contents entries kept from one book.
///
/// A novel has tens and a reference work has hundreds. This is the point past
/// which a contents screen has stopped being a way to find a chapter, and it
/// also bounds what a book with a generated entry per paragraph can make this
/// crate build.
const MAX_CONTENTS: usize = 2_048;

/// How deep a contents entry may be nested before the nesting is flattened.
///
/// Three is a part, a chapter and a section, which is as much structure as a
/// screen this size can indent and still leave room for the words.
const MAX_CONTENTS_DEPTH: u8 = 3;

/// Reads the book's own table of contents, if it published one this can use.
///
/// EPUB 3 states it in a navigation document and EPUB 2 in an NCX, and books
/// carrying both are common, because a publisher who moved to EPUB 3 still
/// wants older readers to open the file. The navigation document is preferred
/// and the NCX is the fallback, which between them covers everything these
/// catalogs actually serve.
///
/// Every entry has to name somewhere in the reading order. One that does not
/// is dropped rather than pointed at the nearest thing: a contents line that
/// goes to the wrong chapter is worse than one that is missing, because the
/// reader cannot tell it went wrong.
fn contents_of(
    archive: &Archive<'_>,
    package: &Package,
    base: &str,
    starts: &[(String, usize)],
    anchors: &BTreeMap<String, usize>,
) -> Vec<Contents> {
    let from_nav = package
        .nav
        .as_ref()
        .and_then(|id| package.manifest.get(id))
        .map(|item| resolve(base, &item.href))
        .and_then(|name| {
            let bytes = archive.read(&name).ok()?;
            let inside = directory_of(&name);
            Some(read_nav(&text_of(&bytes), &inside))
        })
        .unwrap_or_default();
    let raw = if from_nav.is_empty() {
        package
            .ncx
            .as_ref()
            .and_then(|id| package.manifest.get(id))
            .map(|item| resolve(base, &item.href))
            .and_then(|name| {
                let bytes = archive.read(&name).ok()?;
                let inside = directory_of(&name);
                Some(read_ncx(&text_of(&bytes), &inside))
            })
            .unwrap_or_default()
    } else {
        from_nav
    };
    raw.into_iter()
        .filter_map(|(title, file, fragment, depth)| {
            let title = collapse(&title);
            if title.is_empty() {
                return None;
            }
            // The fragment first, because it is the finer answer and often the
            // only true one: Gutenberg puts every chapter of a novel in one
            // file and separates them by name alone, so resolving to the file
            // would put the whole contents on page one.
            let block = fragment
                .and_then(|fragment| anchors.get(&format!("{file}#{fragment}")).copied())
                .or_else(|| {
                    starts
                        .iter()
                        .find(|(name, _)| *name == file)
                        .map(|(_, block)| *block)
                })?;
            Some(Contents {
                title,
                block,
                depth: depth.min(MAX_CONTENTS_DEPTH),
            })
        })
        .take(MAX_CONTENTS)
        .collect()
}

/// Reads an EPUB 3 navigation document's `toc` nav.
///
/// A navigation document holds several navs -- a table of contents, a list of
/// illustrations, a set of landmarks -- and only the one marked `toc` is the
/// contents. The marking is `epub:type`, but the prefix is chosen by whoever
/// wrote the file, so the attribute is matched by its local name.
fn read_nav(xml: &str, base: &str) -> Vec<(String, String, Option<String>, u8)> {
    let mut found = Vec::new();
    let mut in_toc = false;
    let mut depth: u8 = 0;
    let mut nav_depth = 0usize;
    let mut href: Option<String> = None;
    for_each_element(xml, |name, inside, closing, before| {
        match (closing, name) {
            (false, "nav") => {
                nav_depth += 1;
                if !in_toc && is_toc_nav(inside) {
                    in_toc = true;
                    nav_depth = 1;
                    depth = 0;
                }
            }
            (true, "nav") => {
                nav_depth = nav_depth.saturating_sub(1);
                if nav_depth == 0 {
                    in_toc = false;
                }
            }
            // An `ol` inside the contents is a level of nesting. The first one
            // is the list itself rather than an indent, so depth counts from
            // the second.
            (false, "ol") if in_toc => depth = depth.saturating_add(1),
            (true, "ol") if in_toc => depth = depth.saturating_sub(1),
            (false, "a") if in_toc => {
                href = attribute(inside, "href").map(decode_entities);
            }
            (true, "a") if in_toc => {
                if let Some(target) = href.take() {
                    found.push((
                        decode_entities(before),
                        resolve(base, &target),
                        fragment_of(&target),
                        depth.saturating_sub(1),
                    ));
                }
            }
            _ => {}
        }
    });
    found
}

/// Whether this `nav` is the one holding the table of contents.
fn is_toc_nav(inside: &str) -> bool {
    inside.split_whitespace().any(|word| {
        let mut parts = word.splitn(2, '=');
        let key = parts.next().unwrap_or_default();
        let local = key.rsplit(':').next().unwrap_or(key);
        local == "type"
            && parts
                .next()
                .is_some_and(|value| value.trim_matches(['"', '\'']).eq_ignore_ascii_case("toc"))
    })
}

/// Reads an EPUB 2 NCX.
///
/// A `navPoint` carries its label before its target and may contain further
/// points, so a parent closes only after all of its children. Emitting an
/// entry when its point closed would therefore put every chapter after its own
/// sections. Each point instead claims its place in the list the moment it
/// opens, and the label and target are written into that place as they arrive,
/// which keeps the contents in the order the book states them.
fn read_ncx(xml: &str, base: &str) -> Vec<(String, String, Option<String>, u8)> {
    let mut found: Vec<(Option<String>, Option<String>, u8)> = Vec::new();
    let mut stack: Vec<usize> = Vec::new();
    let mut in_label = false;
    for_each_element(xml, |name, inside, closing, before| {
        // Lower case throughout, because `element_name` folds the case it was
        // written in: an NCX spells these `navPoint` and `navLabel`, and
        // matching them the way the file does finds nothing at all.
        let local = name.rsplit(':').next().unwrap_or(name);
        match (closing, local) {
            (false, "navpoint") => {
                let depth = u8::try_from(stack.len()).unwrap_or(u8::MAX);
                stack.push(found.len());
                found.push((None, None, depth));
            }
            (true, "navpoint") => {
                stack.pop();
            }
            (false, "navlabel") => in_label = true,
            (true, "navlabel") => in_label = false,
            (true, "text") if in_label => {
                if let Some(entry) = stack.last().and_then(|at| found.get_mut(*at)) {
                    if entry.0.is_none() {
                        entry.0 = Some(decode_entities(before));
                    }
                }
            }
            (false, "content") => {
                if let Some(entry) = stack.last().and_then(|at| found.get_mut(*at)) {
                    if entry.1.is_none() {
                        entry.1 = attribute(inside, "src").map(decode_entities);
                    }
                }
            }
            _ => {}
        }
    });
    found
        .into_iter()
        .filter_map(|(title, target, depth)| {
            let target = target?;
            Some((title?, resolve(base, &target), fragment_of(&target), depth))
        })
        .collect()
}

/// The most bytes of pictures carried out of one book.
///
/// An illustrated Gutenberg edition runs to twenty-five megabytes of plates,
/// and this device shares its memory with the reader it is pretending not to
/// be. Eight is enough for the illustrations of a novel at the size this panel
/// can show, and is the point past which a book of photographs stops being
/// something to open on a reader.
const MAX_IMAGE_BYTES: usize = 8 * 1024 * 1024;

/// The most bytes one picture may take.
///
/// A plate scanned at print resolution is several megabytes and will be drawn
/// at ninety millimetres on a greyscale panel. Refusing the largest ones
/// costs a picture and saves the book.
const MAX_ONE_IMAGE_BYTES: usize = 2 * 1024 * 1024;

/// Reads the pictures the assembled book refers to, and only those.
///
/// A book's archive holds cover art, publisher marks and the stylesheet's own
/// decorations that no page refers to, so the blocks decide what is worth
/// carrying rather than the manifest.
fn images_of(archive: &Archive<'_>, builder: &Builder) -> BTreeMap<String, Vec<u8>> {
    let mut images: BTreeMap<String, Vec<u8>> = BTreeMap::new();
    let mut total = 0usize;
    for block in builder.blocks() {
        let Block::Picture { name, .. } = block else {
            continue;
        };
        if images.contains_key(name) {
            continue;
        }
        let Ok(bytes) = archive.read(name) else {
            continue;
        };
        if bytes.len() > MAX_ONE_IMAGE_BYTES || total.saturating_add(bytes.len()) > MAX_IMAGE_BYTES {
            continue;
        }
        total += bytes.len();
        images.insert(name.clone(), bytes);
    }
    images
}

/// Removes a table of contents printed into the middle of the book.
///
/// A book's contents is navigation, not prose, and the reader now has the real
/// one on a screen of its own. Left in, it arrives as a wall of chapter
/// numbers: Project Gutenberg writes its contents as a `<p class="toc">` full
/// of links separated by line breaks, and a line break is folded into a space
/// by the paginator, so sixty-one chapter numbers become one paragraph. That
/// paragraph was the first thing a reader saw on opening Pride and Prejudice.
///
/// Marked by three different conventions and any of them will do: the EPUB 3
/// semantic `epub:type`, the publishing ARIA role, and the class Gutenberg
/// actually writes. Only the element's own text goes -- the rest of the file
/// is left exactly as it was, because a contents block sits inside a title
/// page often enough that dropping the whole file would take the title with
/// it.
fn strip_toc(xml: &str) -> String {
    let mut out = String::with_capacity(xml.len());
    let mut rest = xml;
    while let Some(at) = rest.find('<') {
        let (before, tail) = rest.split_at(at);
        out.push_str(before);
        let Some(end) = tail.find('>') else {
            out.push_str(tail);
            return out;
        };
        let inside = &tail[1..end];
        let name = element_name(inside);
        if !inside.starts_with('/') && is_contents_element(inside) {
            rest = skip_element(&tail[end + 1..], &name);
            continue;
        }
        out.push_str(&tail[..=end]);
        rest = &tail[end + 1..];
    }
    out.push_str(rest);
    out
}

/// Whether an element is marked as a table of contents.
fn is_contents_element(inside: &str) -> bool {
    for (key, wanted) in [("type", "toc"), ("role", "doc-toc"), ("class", "toc")] {
        let Some(value) = attribute(inside, key) else {
            continue;
        };
        // `class` and `epub:type` are both space-separated lists, so the mark
        // has to be one of the words: a `class="tocsomething"` is not a table
        // of contents, and neither is `class="not-toc"`.
        if value
            .split_whitespace()
            .any(|word| word.eq_ignore_ascii_case(wanted))
        {
            return true;
        }
    }
    false
}

/// The part of an href after the `#`, when it names one.
///
/// Kept apart from [`resolve`], which drops it deliberately: a fragment is a
/// place inside a file rather than a different file, so it is the wrong thing
/// to look up in an archive and the right thing to look up in a book.
fn fragment_of(href: &str) -> Option<String> {
    href.split_once('#')
        .map(|(_, fragment)| fragment.to_owned())
        .filter(|fragment| !fragment.is_empty())
}

/// Finds the package document.
///
/// The container names it. When the container is missing or says nothing
/// usable (which happens, because it is the one file every tool assumes
/// somebody else wrote) the archive is searched for the one file that ends in
/// `.opf`, which is what a person would do.
// `Path::extension` is what the lint suggests, and it is wrong here: these are
// zip member names, not paths on this machine, and on Windows `Path` would take
// a backslash for a separator when a zip's separator is always a slash. The
// names have already been lower-cased where it matters.
#[allow(clippy::case_sensitive_file_extension_comparisons)]
fn find_package(archive: &Archive<'_>) -> Option<String> {
    if let Ok(container) = archive.read(CONTAINER) {
        if let Some(path) = root_file(&text_of(&container)) {
            return Some(path);
        }
    }
    archive
        .names()
        .find(|name| name.ends_with(".opf"))
        .map(str::to_owned)
}

/// The path the container points at.
fn root_file(xml: &str) -> Option<String> {
    let mut found = None;
    for_each_element(xml, |name, inside, closing, _| {
        if !closing && name == "rootfile" && found.is_none() {
            found = attribute(inside, "full-path")
                .map(decode_entities)
                .filter(|path| !path.trim().is_empty());
        }
    });
    found
}

/// One file listed in the package's manifest.
struct Item {
    href: String,
    media_type: String,
}

/// What the package document says.
struct Package {
    title: Option<String>,
    author: Option<String>,
    manifest: BTreeMap<String, Item>,
    /// Spine entries in order, each with whether it is part of the main flow.
    spine: Vec<(String, bool)>,
    /// The identifier of the EPUB 3 navigation document, when the manifest
    /// marks one with `properties="nav"`.
    nav: Option<String>,
    /// The identifier the spine's `toc` attribute names, which is how EPUB 2
    /// points at its NCX.
    ///
    /// Both are kept because both are found in the wild, often in the same
    /// book: an EPUB 3 that still ships an NCX so that older readers can open
    /// it. The navigation document is preferred when there is one, and the NCX
    /// is what the great majority of Project Gutenberg's books actually carry.
    ncx: Option<String>,
}

impl Package {
    /// The identifiers to read, in order.
    ///
    /// Entries marked `linear="no"` are outside the reading flow (a cover
    /// page, a set of endnotes reached by a link) and are left out. But a
    /// book whose *every* entry is marked that way is a book somebody's tool
    /// mislabelled, and honouring the marking there yields nothing at all, so
    /// in that case the marking is ignored and the whole spine is read.
    fn reading_order(&self) -> impl Iterator<Item = &String> {
        let any_linear = self.spine.iter().any(|(_, linear)| *linear);
        self.spine
            .iter()
            .filter(move |(_, linear)| *linear || !any_linear)
            .map(|(id, _)| id)
    }
}

/// Reads the package document.
fn read_package(xml: &str) -> Package {
    let mut package = Package {
        title: None,
        author: None,
        manifest: BTreeMap::new(),
        spine: Vec::new(),
        nav: None,
        ncx: None,
    };
    // The same element names appear in more than one place (`<title>` is in
    // the metadata and also in a `<guide>` reference) so the section matters.
    let mut in_metadata = false;
    for_each_element(xml, |name, inside, closing, before| {
        // A namespace prefix is chosen by whoever wrote the file. `dc:title`
        // and a `title` under a default Dublin Core namespace are the same
        // element, and the prefix is not worth resolving properly for the two
        // fields being read.
        let local = name.rsplit(':').next().unwrap_or(name);
        match (closing, local) {
            (false, "metadata") => in_metadata = true,
            (true, "metadata") => in_metadata = false,
            (true, "title") if in_metadata && package.title.is_none() => {
                package.title = Some(decode_entities(before));
            }
            (true, "creator") if in_metadata && package.author.is_none() => {
                package.author = Some(decode_entities(before));
            }
            (false, "item") => {
                let id = attribute(inside, "id").map(decode_entities);
                let href = attribute(inside, "href").map(decode_entities);
                if let (Some(id), Some(href)) = (id, href) {
                    // `properties` is a space-separated list, so `nav` has to
                    // be matched as one of its words: a stylesheet marked
                    // `navigation-only` is not the navigation document.
                    if attribute(inside, "properties")
                        .is_some_and(|properties| properties.split_whitespace().any(|word| word == "nav"))
                    {
                        package.nav = Some(id.clone());
                    }
                    package.manifest.insert(
                        id,
                        Item {
                            href,
                            media_type: attribute(inside, "media-type")
                                .unwrap_or_default()
                                .to_ascii_lowercase(),
                        },
                    );
                }
            }
            (false, "spine") => {
                package.ncx = attribute(inside, "toc").map(decode_entities);
            }
            (false, "itemref") => {
                if let Some(id) = attribute(inside, "idref").map(decode_entities) {
                    let linear = attribute(inside, "linear")
                        .is_none_or(|value| !value.eq_ignore_ascii_case("no"));
                    package.spine.push((id, linear));
                }
            }
            _ => {}
        }
    });
    package
}

/// Whether a manifest entry is something with words in it.
///
/// The media type is checked first because it is what the specification says
/// to use, and the extension second because a manifest with no media types in
/// it is a thing that exists.
#[allow(clippy::case_sensitive_file_extension_comparisons)]
fn is_readable(media_type: &str, href: &str) -> bool {
    if !media_type.is_empty() {
        return media_type.contains("xhtml") || media_type.contains("text/html");
    }
    let path = href.split(['#', '?']).next().unwrap_or(href);
    let lower = path.to_ascii_lowercase();
    lower.ends_with(".xhtml") || lower.ends_with(".html") || lower.ends_with(".htm")
}

/// Walks the elements of an XML document.
///
/// A scan, not a parser: XML's well-formedness rules are not checked and its
/// namespaces are not resolved, because the only thing wanted here is a
/// handful of elements and their attributes. `before` is the text since the
/// previous tag, which is how an element's content is read.
fn for_each_element(xml: &str, mut visit: impl FnMut(&str, &str, bool, &str)) {
    let mut rest = xml;
    while let Some(at) = rest.find('<') {
        let before = &rest[..at];
        let tail = &rest[at..];
        if let Some(after) = skip_bracketed(tail) {
            rest = after;
            continue;
        }
        let Some(end) = tail.find('>') else {
            return;
        };
        let inside = &tail[1..end];
        rest = &tail[end + 1..];
        // A processing instruction (`<?xml … ?>`) is not an element.
        if inside.starts_with('?') || inside.starts_with('!') {
            continue;
        }
        let name = element_name(inside);
        visit(&name, inside, inside.starts_with('/'), before);
        // A tag that closes itself both opens and closes. Without this, the
        // text after `<title/>` would be read as the title's content.
        if inside.ends_with('/') && !inside.starts_with('/') {
            visit(&name, inside, true, "");
        }
    }
}

/// The directory part of a path, with its trailing separator.
fn directory_of(path: &str) -> String {
    match path.rfind('/') {
        Some(at) => path[..=at].to_owned(),
        None => String::new(),
    }
}

/// Turns an href from the package into a path into the archive.
///
/// Three things happen: the fragment goes, because `chapter1.xhtml#part2` is a
/// place inside a file rather than a different file; percent escapes are
/// undone, because a filename with a space in it is written `%20` in an href
/// and stored with a space in the archive; and `..` is resolved, because a
/// package in `OEBPS/` referring to `../images/a.png` means the archive root.
fn resolve(base: &str, href: &str) -> String {
    let path = href.split(['#', '?']).next().unwrap_or(href);
    let path = unescape(path);
    let joined = if path.starts_with('/') {
        path.trim_start_matches('/').to_owned()
    } else {
        format!("{base}{path}")
    };
    let mut parts: Vec<&str> = Vec::new();
    for part in joined.split('/') {
        match part {
            "" | "." => {}
            ".." => {
                parts.pop();
            }
            other => parts.push(other),
        }
    }
    parts.join("/")
}

/// Undoes percent escapes, leaving anything that is not one alone.
fn unescape(path: &str) -> String {
    if !path.contains('%') {
        return path.to_owned();
    }
    let mut out: Vec<u8> = Vec::with_capacity(path.len());
    let bytes = path.as_bytes();
    let mut at = 0;
    while at < bytes.len() {
        // A `%` that is not followed by two hex digits is a literal `%`, which
        // is a character a filename is allowed to contain.
        if bytes[at] == b'%' && at + 2 < bytes.len() {
            let hex = &path[at + 1..at + 3];
            if let Ok(byte) = u8::from_str_radix(hex, 16) {
                out.push(byte);
                at += 3;
                continue;
            }
        }
        out.push(bytes[at]);
        at += 1;
    }
    String::from_utf8_lossy(&out).into_owned()
}

/// Reads a member's bytes as text.
///
/// EPUB allows UTF-8 and UTF-16. UTF-16 is vanishingly rare and completely
/// unreadable if guessed wrong (every character of the book comes out as a
/// pair of wrong ones) so the byte-order mark is honoured where there is one.
fn text_of(bytes: &[u8]) -> String {
    if let Some(body) = bytes.strip_prefix(&[0xef, 0xbb, 0xbf]) {
        return String::from_utf8_lossy(body).into_owned();
    }
    for (mark, big_endian) in [([0xfe_u8, 0xff_u8], true), ([0xff, 0xfe], false)] {
        if let Some(body) = bytes.strip_prefix(&mark[..]) {
            let units: Vec<u16> = body
                .chunks_exact(2)
                .map(|pair| {
                    if big_endian {
                        u16::from_be_bytes([pair[0], pair[1]])
                    } else {
                        u16::from_le_bytes([pair[0], pair[1]])
                    }
                })
                .collect();
            return String::from_utf16_lossy(&units);
        }
    }
    String::from_utf8_lossy(bytes).into_owned()
}

/// One chapter to write, as a title and its prose.
///
/// The body is plain text in which a blank line starts a new paragraph, which
/// is how prose arrives from a person typing and from a language model, and
/// spares every caller from having to hand-write XHTML.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Chapter {
    pub title: String,
    pub body: String,
}

/// Writes an EPUB.
///
/// The layout is deliberately the plainest one that is still a real EPUB:
/// EPUB 2 with an NCX, because that is what the widest range of readers will
/// open, including the firmware's own. A generated book has no cover image, no
/// stylesheet and no scripts, and inventing them would only add files that
/// could be wrong.
///
/// Two details of the container format are not optional and are easy to get
/// wrong. `mimetype` must be the archive's first member and must be stored
/// rather than deflated, which is why it is pushed first and why
/// [`zip::stored`] is the right writer: it stores every member and preserves
/// the order it is given.
///
/// The identifier is derived from the title rather than randomly generated, so
/// that writing the same book twice produces the same bytes. A reproducible
/// output is worth more here than a globally unique one, and no random source
/// is available to this crate anyway.
///
/// # Errors
///
/// Returns [`zip::Fault`] when the archive cannot be represented, which for a
/// book of text means it is far past four gigabytes.
pub fn write(
    title: &str,
    author: Option<&str>,
    chapters: &[Chapter],
) -> Result<Vec<u8>, zip::Fault> {
    let identifier = format!("urn:cobalt:{}", slug(title));
    let mut manifest = String::new();
    let mut spine = String::new();
    let mut nav = String::new();
    let mut files: Vec<(String, Vec<u8>)> = Vec::with_capacity(chapters.len());
    for (index, chapter) in chapters.iter().enumerate() {
        let id = format!("ch{}", index + 1);
        let href = format!("{id}.xhtml");
        let _ = writeln!(
            manifest,
            "    <item id=\"{id}\" href=\"{href}\" media-type=\"application/xhtml+xml\"/>"
        );
        let _ = writeln!(spine, "    <itemref idref=\"{id}\"/>");
        let _ = write!(
            nav,
            "    <navPoint id=\"nav-{id}\" playOrder=\"{}\">\n      \
             <navLabel><text>{}</text></navLabel>\n      \
             <content src=\"{href}\"/>\n    </navPoint>\n",
            index + 1,
            escape(&chapter.title),
        );
        files.push((
            format!("OEBPS/{href}"),
            chapter_xhtml(&chapter.title, &chapter.body).into_bytes(),
        ));
    }

    // mimetype first, and stored, or it is not an EPUB whatever else is right.
    let mut members = vec![
        ("mimetype".to_owned(), b"application/epub+zip".to_vec()),
        (CONTAINER.to_owned(), container_xml().into_bytes()),
        (
            "OEBPS/content.opf".to_owned(),
            package_opf(title, author, &identifier, &manifest, &spine).into_bytes(),
        ),
        (
            "OEBPS/toc.ncx".to_owned(),
            toc_ncx(title, &identifier, &nav).into_bytes(),
        ),
    ];
    members.append(&mut files);
    zip::stored(&members)
}

fn container_xml() -> String {
    String::from(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <container version=\"1.0\" \
         xmlns=\"urn:oasis:names:tc:opendocument:xmlns:container\">\n  \
         <rootfiles>\n    \
         <rootfile full-path=\"OEBPS/content.opf\" \
         media-type=\"application/oebps-package+xml\"/>\n  \
         </rootfiles>\n</container>\n",
    )
}

fn package_opf(
    title: &str,
    author: Option<&str>,
    identifier: &str,
    manifest: &str,
    spine: &str,
) -> String {
    let creator = author.map_or_else(String::new, |author| {
        format!(
            "    <dc:creator opf:role=\"aut\">{}</dc:creator>\n",
            escape(author)
        )
    });
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <package xmlns=\"http://www.idpf.org/2007/opf\" version=\"2.0\" \
         unique-identifier=\"bookid\">\n  \
         <metadata xmlns:dc=\"http://purl.org/dc/elements/1.1/\" \
         xmlns:opf=\"http://www.idpf.org/2007/opf\">\n    \
         <dc:title>{}</dc:title>\n{creator}    \
         <dc:language>en</dc:language>\n    \
         <dc:identifier id=\"bookid\">{}</dc:identifier>\n  \
         </metadata>\n  <manifest>\n    \
         <item id=\"ncx\" href=\"toc.ncx\" media-type=\"application/x-dtbncx+xml\"/>\n\
         {manifest}  </manifest>\n  <spine toc=\"ncx\">\n{spine}  </spine>\n</package>\n",
        escape(title),
        escape(identifier),
    )
}

fn toc_ncx(title: &str, identifier: &str, nav: &str) -> String {
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <ncx xmlns=\"http://www.daisy.org/z3986/2005/ncx/\" version=\"2005-1\">\n  \
         <head>\n    <meta name=\"dtb:uid\" content=\"{}\"/>\n    \
         <meta name=\"dtb:depth\" content=\"1\"/>\n    \
         <meta name=\"dtb:totalPageCount\" content=\"0\"/>\n    \
         <meta name=\"dtb:maxPageNumber\" content=\"0\"/>\n  </head>\n  \
         <docTitle><text>{}</text></docTitle>\n  <navMap>\n{nav}  </navMap>\n</ncx>\n",
        escape(identifier),
        escape(title),
    )
}

fn chapter_xhtml(title: &str, body: &str) -> String {
    let mut prose = String::new();
    for paragraph in paragraphs(body) {
        let _ = writeln!(prose, "<p>{}</p>", escape(&paragraph));
    }
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <!DOCTYPE html>\n\
         <html xmlns=\"http://www.w3.org/1999/xhtml\">\n\
         <head><title>{0}</title></head>\n\
         <body>\n<h1>{0}</h1>\n{prose}</body>\n</html>\n",
        escape(title),
    )
}

/// Splits prose into paragraphs on blank lines.
fn paragraphs(body: &str) -> Vec<String> {
    let normalised = crate::normalise_breaks(body);
    let mut out = Vec::new();
    let mut current = String::new();
    for line in normalised.split('\n') {
        if line.trim().is_empty() {
            if !current.trim().is_empty() {
                out.push(current.trim().to_owned());
            }
            current.clear();
        } else {
            if !current.is_empty() {
                current.push(' ');
            }
            current.push_str(line.trim());
        }
    }
    if !current.trim().is_empty() {
        out.push(current.trim().to_owned());
    }
    out
}

/// Escapes text for use in XML content or in a double-quoted attribute.
///
/// All five characters are escaped regardless of position so that one function
/// is safe in both places. Control characters that XML forbids outright are
/// dropped rather than escaped, because there is no spelling of them that a
/// conforming parser will accept.
fn escape(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for character in text.chars() {
        match character {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            '\t' | '\n' => out.push(character),
            control if control < ' ' || control == '\u{7f}' => {}
            other => out.push(other),
        }
    }
    out
}

/// A lowercase identifier safe to put in a URN.
fn slug(title: &str) -> String {
    let mut out = String::new();
    for character in title.chars() {
        if character.is_ascii_alphanumeric() {
            out.extend(character.to_lowercase());
        } else if !out.ends_with('-') && !out.is_empty() {
            out.push('-');
        }
    }
    let trimmed = out.trim_end_matches('-');
    if trimmed.is_empty() {
        "book".to_owned()
    } else {
        trimmed.to_owned()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::zip::tests::archive;

    const CONTAINER_XML: &str = r#"<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/book.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>"#;

    fn opf(spine: &str, manifest: &str) -> String {
        format!(
            r#"<?xml version="1.0"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:title>A Book</dc:title>
    <dc:creator>A Person</dc:creator>
  </metadata>
  <manifest>{manifest}</manifest>
  <spine>{spine}</spine>
</package>"#
        )
    }

    fn a_book() -> Vec<u8> {
        let package = opf(
            r#"<itemref idref="one"/><itemref idref="two"/>"#,
            r#"<item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>
               <item id="two" href="two.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        archive(&[
            ("mimetype", b"application/epub+zip"),
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            (
                "OEBPS/one.xhtml",
                b"<html><body><h1>Chapter One</h1><p>It began badly.</p></body></html>",
            ),
            (
                "OEBPS/two.xhtml",
                b"<html><body><h1>Chapter Two</h1><p>It got worse.</p></body></html>",
            ),
        ])
    }

    #[test]
    fn a_book_comes_back_in_its_reading_order() {
        let document = parse(&a_book()).expect("a readable book");
        let words: Vec<&str> = document
            .blocks
            .iter()
            .filter_map(|block| block.text())
            .collect();
        assert_eq!(
            words,
            vec![
                "Chapter One",
                "It began badly.",
                "Chapter Two",
                "It got worse."
            ]
        );
    }

    #[test]
    fn the_package_says_what_the_book_is_and_the_chapters_do_not_overrule_it() {
        let document = parse(&a_book()).expect("a readable book");
        assert_eq!(document.title.as_deref(), Some("A Book"));
        assert_eq!(document.author.as_deref(), Some("A Person"));
    }

    /// A book whose whole contents live in one file, told apart by fragment.
    ///
    /// This is Project Gutenberg's shape, not a contrived one: its EPUBs put a
    /// novel's every chapter in a single document and separate them by name
    /// alone, so a reader that resolves a contents entry to a file puts the
    /// entire table of contents on page one.
    fn one_file_with_named_chapters(toc: &str, toc_item: &str) -> Vec<u8> {
        let package = format!(
            r#"<?xml version="1.0"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>A Book</dc:title></metadata>
  <manifest>
    <item id="body" href="body.xhtml" media-type="application/xhtml+xml"/>
    {toc_item}
  </manifest>
  <spine toc="ncx"><itemref idref="body"/></spine>
</package>"#
        );
        archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            (
                "OEBPS/body.xhtml",
                br#"<h1 id="one">Chapter One</h1><p>The first words.</p>
                    <h1 id="two">Chapter Two</h1><p>The second words.</p>"#,
            ),
            ("OEBPS/toc.ncx", toc.as_bytes()),
        ])
    }

    const NCX_ITEM: &str = r#"<item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>"#;

    #[test]
    fn a_books_own_table_of_contents_is_read_rather_than_guessed_at() {
        let ncx = r#"<?xml version="1.0"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/"><navMap>
  <navPoint id="a"><navLabel><text>Chapter One</text></navLabel>
    <content src="body.xhtml#one"/></navPoint>
  <navPoint id="b"><navLabel><text>Chapter Two</text></navLabel>
    <content src="body.xhtml#two"/></navPoint>
</navMap></ncx>"#;
        let document = parse(&one_file_with_named_chapters(ncx, NCX_ITEM)).expect("a readable book");
        let titles: Vec<&str> = document
            .contents
            .iter()
            .map(|entry| entry.title.as_str())
            .collect();
        assert_eq!(titles, ["Chapter One", "Chapter Two"]);
    }

    #[test]
    fn two_chapters_in_one_file_do_not_land_on_the_same_page() {
        // The whole reason fragments are resolved. Without it both entries
        // point at the first block of the only file and the contents lies.
        let ncx = r#"<?xml version="1.0"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/"><navMap>
  <navPoint id="a"><navLabel><text>Chapter One</text></navLabel>
    <content src="body.xhtml#one"/></navPoint>
  <navPoint id="b"><navLabel><text>Chapter Two</text></navLabel>
    <content src="body.xhtml#two"/></navPoint>
</navMap></ncx>"#;
        let document = parse(&one_file_with_named_chapters(ncx, NCX_ITEM)).expect("a readable book");
        assert_ne!(
            document.contents[0].block, document.contents[1].block,
            "both chapters resolved to the same block"
        );
        assert_eq!(
            document.blocks[document.contents[1].block].text(),
            Some("Chapter Two")
        );
    }

    #[test]
    fn a_chapter_that_closes_after_its_own_sections_still_comes_before_them() {
        // An NCX nests, so a parent point closes only once its children have.
        // Emitting an entry when its point closed put every chapter after its
        // own sections, which is the contents in very nearly the wrong order.
        let ncx = r#"<?xml version="1.0"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/"><navMap>
  <navPoint id="a"><navLabel><text>Chapter One</text></navLabel>
    <content src="body.xhtml#one"/>
    <navPoint id="a1"><navLabel><text>Chapter Two</text></navLabel>
      <content src="body.xhtml#two"/></navPoint>
  </navPoint>
</navMap></ncx>"#;
        let document = parse(&one_file_with_named_chapters(ncx, NCX_ITEM)).expect("a readable book");
        let titles: Vec<&str> = document
            .contents
            .iter()
            .map(|entry| entry.title.as_str())
            .collect();
        assert_eq!(titles, ["Chapter One", "Chapter Two"]);
        assert_eq!(document.contents[0].depth, 0);
        assert_eq!(document.contents[1].depth, 1, "the nesting was lost");
    }

    #[test]
    fn an_epub_3_navigation_document_is_preferred_over_an_ncx() {
        // Books carrying both are ordinary: a publisher who moved to EPUB 3
        // keeps an NCX so that older readers still open the file.
        let ncx = r#"<?xml version="1.0"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/"><navMap>
  <navPoint id="a"><navLabel><text>From the NCX</text></navLabel>
    <content src="body.xhtml#one"/></navPoint>
</navMap></ncx>"#;
        let package = r#"<?xml version="1.0"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>A Book</dc:title></metadata>
  <manifest>
    <item id="body" href="body.xhtml" media-type="application/xhtml+xml"/>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
    <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>
  </manifest>
  <spine toc="ncx"><itemref idref="body"/></spine>
</package>"#;
        let nav = r#"<html><body>
  <nav epub:type="landmarks"><ol><li><a href="body.xhtml#one">Not the contents</a></li></ol></nav>
  <nav epub:type="toc"><ol>
    <li><a href="body.xhtml#one">From the nav</a></li>
    <li><a href="body.xhtml#two">Chapter Two</a></li>
  </ol></nav>
</body></html>"#;
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            (
                "OEBPS/body.xhtml",
                br#"<h1 id="one">Chapter One</h1><p>Words.</p><h1 id="two">Chapter Two</h1><p>More.</p>"#,
            ),
            ("OEBPS/toc.ncx", ncx.as_bytes()),
            ("OEBPS/nav.xhtml", nav.as_bytes()),
        ]);
        let document = parse(&bytes).expect("a readable book");
        assert_eq!(document.contents[0].title, "From the nav");
        assert_eq!(
            document.contents.len(),
            2,
            "the landmarks nav was read as contents"
        );
    }

    #[test]
    fn a_contents_printed_into_the_book_is_not_read_as_prose() {
        // Gutenberg writes its contents as a paragraph of links separated by
        // line breaks, and a line break folds into a space, so sixty-one
        // chapter numbers arrive as one paragraph. It was the first thing a
        // reader saw on opening the book.
        let package = opf(
            r#"<itemref idref="one"/>"#,
            r#"<item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            (
                "OEBPS/one.xhtml",
                br##"<h1>A Book</h1>
                    <p class="toc"><a href="#a">Chapter I.</a><br/><a href="#b">Chapter II.</a></p>
                    <p>The book itself begins.</p>"##,
            ),
        ]);
        let document = parse(&bytes).expect("a readable book");
        let words: Vec<&str> = document
            .blocks
            .iter()
            .filter_map(|block| block.text())
            .collect();
        assert!(
            !words.iter().any(|text| text.contains("Chapter I.")),
            "the contents was read as prose: {words:?}"
        );
        assert!(
            words.iter().any(|text| text.contains("The book itself")),
            "the rest of the file went with it: {words:?}"
        );
        assert!(
            words.iter().any(|text| text.contains("A Book")),
            "the title went with it: {words:?}"
        );
    }

    #[test]
    fn a_class_that_merely_starts_with_toc_is_not_a_contents() {
        // `class` is a list of words and a contents is one of them. Matching
        // it as a substring would take a `tocsin` out of a book about bells.
        let package = opf(
            r#"<itemref idref="one"/>"#,
            r#"<item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            (
                "OEBPS/one.xhtml",
                br#"<p class="tocsin">The bell rang.</p><p class="not-toc">So did this one.</p>"#,
            ),
        ]);
        let document = parse(&bytes).expect("a readable book");
        let words: Vec<&str> = document
            .blocks
            .iter()
            .filter_map(|block| block.text())
            .collect();
        assert!(words.iter().any(|text| text.contains("The bell rang")), "{words:?}");
        assert!(words.iter().any(|text| text.contains("So did this one")), "{words:?}");
    }

    #[test]
    fn a_contents_entry_naming_nothing_in_the_book_is_dropped() {
        // Pointing it at the nearest block would send a reader somewhere the
        // book never said, and they would have no way to tell it went wrong.
        let ncx = r#"<?xml version="1.0"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/"><navMap>
  <navPoint id="a"><navLabel><text>Chapter One</text></navLabel>
    <content src="body.xhtml#one"/></navPoint>
  <navPoint id="b"><navLabel><text>A Chapter That Is Not Here</text></navLabel>
    <content src="missing.xhtml"/></navPoint>
</navMap></ncx>"#;
        let document = parse(&one_file_with_named_chapters(ncx, NCX_ITEM)).expect("a readable book");
        let titles: Vec<&str> = document
            .contents
            .iter()
            .map(|entry| entry.title.as_str())
            .collect();
        assert_eq!(titles, ["Chapter One"]);
    }

    #[test]
    fn a_named_place_can_be_found_after_the_licence_is_stripped_off_the_front() {
        // Gutenberg's boilerplate is removed once the book is assembled, which
        // moves every block. An anchor that was not moved with them points at
        // whatever happens to sit at the old index.
        let package = opf(
            r#"<itemref idref="one"/>"#,
            r#"<item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let body = format!(
            r#"<p>{}</p><p>Front matter nobody reads.</p><h1 id="start">Chapter One</h1><p>The book.</p>"#,
            crate::GUTENBERG_START
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/one.xhtml", body.as_bytes()),
        ]);
        let document = parse(&bytes).expect("a readable book");
        let at = document
            .anchors
            .get("OEBPS/one.xhtml#start")
            .copied()
            .expect("the anchor survived the strip");
        assert_eq!(document.blocks[at].text(), Some("Chapter One"));
    }

    #[test]
    fn each_file_is_a_part_that_can_be_navigated_to() {
        let document = parse(&a_book()).expect("a readable book");
        assert_eq!(document.parts().len(), 2, "{:?}", document.blocks);
        assert_eq!(document.part_title(0), Some("Chapter One"));
    }

    #[test]
    fn the_spine_and_not_the_archive_decides_the_order() {
        // The archive is sorted by name, so a book whose chapters are `a`, `b`
        // and `c` reads correctly by accident. This one does not.
        let package = opf(
            r#"<itemref idref="second"/><itemref idref="first"/>"#,
            r#"<item id="first" href="a.xhtml" media-type="application/xhtml+xml"/>
               <item id="second" href="z.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/a.xhtml", b"<p>Last.</p>"),
            ("OEBPS/z.xhtml", b"<p>First.</p>"),
        ]);
        let document = parse(&bytes).expect("a readable book");
        let words: Vec<&str> = document
            .blocks
            .iter()
            .filter_map(|block| block.text())
            .collect();
        assert_eq!(words, vec!["First.", "Last."]);
    }

    #[test]
    fn an_href_with_an_escape_in_it_still_finds_its_file() {
        let package = opf(
            r#"<itemref idref="one"/>"#,
            r#"<item id="one" href="my%20chapter.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/my chapter.xhtml", b"<p>Found.</p>"),
        ]);
        let document = parse(&bytes).expect("a readable book");
        assert_eq!(document.blocks[0].text(), Some("Found."));
    }

    #[test]
    fn an_href_that_climbs_out_of_the_package_directory_is_followed() {
        let package = opf(
            r#"<itemref idref="one"/>"#,
            r#"<item id="one" href="../text/one.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("text/one.xhtml", b"<p>Found.</p>"),
        ]);
        let document = parse(&bytes).expect("a readable book");
        assert_eq!(document.blocks[0].text(), Some("Found."));
    }

    #[test]
    fn a_fragment_is_a_place_in_a_file_and_not_a_different_file() {
        let package = opf(
            r#"<itemref idref="one"/>"#,
            r#"<item id="one" href="one.xhtml#part2" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/one.xhtml", b"<p>Found.</p>"),
        ]);
        assert_eq!(
            parse(&bytes).expect("a readable book").blocks[0].text(),
            Some("Found.")
        );
    }

    #[test]
    fn a_broken_link_costs_one_chapter_and_not_the_book() {
        let package = opf(
            r#"<itemref idref="missing"/><itemref idref="gone"/><itemref idref="one"/>"#,
            r#"<item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>
               <item id="gone" href="nowhere.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/one.xhtml", b"<p>Still here.</p>"),
        ]);
        let document = parse(&bytes).expect("a readable book");
        assert_eq!(document.blocks[0].text(), Some("Still here."));
    }

    #[test]
    fn a_picture_in_the_manifest_is_not_read_as_prose() {
        let package = opf(
            r#"<itemref idref="art"/><itemref idref="one"/>"#,
            r#"<item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>
               <item id="art" href="cover.png" media-type="image/png"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/one.xhtml", b"<p>Words.</p>"),
            ("OEBPS/cover.png", &[0x89, b'P', b'N', b'G']),
        ]);
        let document = parse(&bytes).expect("a readable book");
        assert_eq!(document.blocks, vec![Block::Paragraph("Words.".to_owned())]);
    }

    #[test]
    fn a_missing_container_is_worked_around_rather_than_refused() {
        // The one file every tool assumes somebody else wrote.
        let package = opf(
            r#"<itemref idref="one"/>"#,
            r#"<item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/one.xhtml", b"<p>Found anyway.</p>"),
        ]);
        assert_eq!(
            parse(&bytes).expect("a readable book").blocks[0].text(),
            Some("Found anyway.")
        );
    }

    #[test]
    fn a_book_whose_every_part_is_marked_ancillary_is_still_read() {
        // Honouring the marking here would leave nothing at all, and a book
        // that opens empty is worse than one that shows its cover page.
        let package = opf(
            r#"<itemref idref="one" linear="no"/>"#,
            r#"<item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/one.xhtml", b"<p>Everything.</p>"),
        ]);
        assert_eq!(
            parse(&bytes).expect("a readable book").blocks[0].text(),
            Some("Everything.")
        );
    }

    #[test]
    fn an_ancillary_part_is_left_out_when_there_is_a_flow_without_it() {
        let package = opf(
            r#"<itemref idref="cover" linear="no"/><itemref idref="one"/>"#,
            r#"<item id="cover" href="cover.xhtml" media-type="application/xhtml+xml"/>
               <item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/cover.xhtml", b"<p>A cover.</p>"),
            ("OEBPS/one.xhtml", b"<p>The book.</p>"),
        ]);
        let document = parse(&bytes).expect("a readable book");
        assert_eq!(
            document.blocks,
            vec![Block::Paragraph("The book.".to_owned())]
        );
    }

    #[test]
    fn an_empty_file_does_not_leave_a_chapter_break_behind_it() {
        let package = opf(
            r#"<itemref idref="blank"/><itemref idref="one"/>"#,
            r#"<item id="blank" href="blank.xhtml" media-type="application/xhtml+xml"/>
               <item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/blank.xhtml", b"<html><body></body></html>"),
            ("OEBPS/one.xhtml", b"<p>The book.</p>"),
        ]);
        let document = parse(&bytes).expect("a readable book");
        assert_eq!(
            document.blocks,
            vec![Block::Paragraph("The book.".to_owned())]
        );
    }

    #[test]
    fn a_file_in_utf_sixteen_is_not_read_as_mojibake() {
        let package = opf(
            r#"<itemref idref="one"/>"#,
            r#"<item id="one" href="one.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let mut wide: Vec<u8> = vec![0xff, 0xfe];
        for unit in "<p>Readable.</p>".encode_utf16() {
            wide.extend_from_slice(&unit.to_le_bytes());
        }
        let bytes = archive(&[
            ("META-INF/container.xml", CONTAINER_XML.as_bytes()),
            ("OEBPS/book.opf", package.as_bytes()),
            ("OEBPS/one.xhtml", &wide),
        ]);
        assert_eq!(
            parse(&bytes).expect("a readable book").blocks[0].text(),
            Some("Readable.")
        );
    }

    #[test]
    fn something_that_is_not_a_book_is_refused_and_says_which_way() {
        assert_eq!(
            parse(b"not a zip"),
            Err(Fault::Archive(zip::Fault::NotAnArchive))
        );
        let empty = archive(&[("readme.txt", b"nothing to read here")]);
        assert_eq!(parse(&empty), Err(Fault::NotABook));
    }

    #[test]
    fn a_self_closing_tag_does_not_swallow_what_follows_it() {
        assert_eq!(root_file(CONTAINER_XML).as_deref(), Some("OEBPS/book.opf"));
        let package = read_package(&opf("", ""));
        assert_eq!(package.title.as_deref(), Some("A Book"));
    }

    #[test]
    fn paths_are_resolved_the_way_a_browser_would() {
        assert_eq!(resolve("OEBPS/", "one.xhtml"), "OEBPS/one.xhtml");
        assert_eq!(resolve("OEBPS/", "../text/one.xhtml"), "text/one.xhtml");
        assert_eq!(resolve("OEBPS/", "./one.xhtml"), "OEBPS/one.xhtml");
        assert_eq!(resolve("OEBPS/", "/one.xhtml"), "one.xhtml");
        assert_eq!(resolve("", "one.xhtml"), "one.xhtml");
        assert_eq!(resolve("a/b/", "../../c.xhtml"), "c.xhtml");
        // Climbing past the root cannot reach outside the archive.
        assert_eq!(resolve("a/", "../../../c.xhtml"), "c.xhtml");
    }

    #[test]
    fn an_escape_that_is_not_one_is_left_alone() {
        assert_eq!(unescape("100%"), "100%");
        assert_eq!(unescape("a%zzb"), "a%zzb");
        assert_eq!(unescape("a%20b"), "a b");
    }

    #[test]
    fn nothing_here_panics_on_anything() {
        let good = a_book();
        for cut in (0..good.len()).step_by(7) {
            let _ = parse(&good[..cut]);
        }
        for at in (0..good.len()).step_by(11) {
            let mut bytes = good.clone();
            bytes[at] ^= 0xff;
            let _ = parse(&bytes);
        }
        for xml in ["", "<", "<?xml", "<rootfile", "<metadata><title>"] {
            let _ = root_file(xml);
            let _ = read_package(xml);
        }
    }

    fn chapters() -> Vec<Chapter> {
        vec![
            Chapter {
                title: "The Sea & the Sky".to_owned(),
                body: "First paragraph.\n\nSecond <paragraph>.".to_owned(),
            },
            Chapter {
                title: "Tides".to_owned(),
                body: "Only one here.".to_owned(),
            },
        ]
    }

    /// The whole point of the writer: what it produces, the parser beside it
    /// must be able to read. A writer verified only against its own expected
    /// bytes can be confidently, consistently wrong.
    #[test]
    fn a_written_book_reads_back_as_the_same_book() {
        let bytes = write("A History of the Moon", Some("Cobalt Audio"), &chapters())
            .expect("a small book fits a zip");
        let document = parse(&bytes).expect("what we wrote must parse");

        assert_eq!(document.title.as_deref(), Some("A History of the Moon"));
        assert_eq!(document.author.as_deref(), Some("Cobalt Audio"));

        // Both chapter titles survive as headings that "next chapter" can find.
        let titles: Vec<&str> = document
            .parts()
            .iter()
            .filter_map(|start| document.part_title(*start))
            .collect();
        assert_eq!(titles, ["The Sea & the Sky", "Tides"]);

        // And the prose, with the markup-looking text intact rather than eaten.
        let prose: Vec<&str> = document
            .blocks
            .iter()
            .filter_map(|block| match block {
                Block::Paragraph(text) => Some(text.as_str()),
                _ => None,
            })
            .collect();
        assert_eq!(
            prose,
            ["First paragraph.", "Second <paragraph>.", "Only one here."]
        );
    }

    /// Sniffing decides which parser runs, so a written book must be
    /// recognisable as an EPUB from its bytes and not only from its name.
    #[test]
    fn a_written_book_is_recognised_as_an_epub() {
        let bytes = write("Book", None, &chapters()).expect("a small book fits a zip");
        assert_eq!(crate::sniff("book.epub", &bytes), crate::Format::Epub);
        assert_eq!(crate::sniff("unnamed", &bytes), crate::Format::Epub);
        assert!(crate::read("book.epub", &bytes).is_ok());
    }

    /// `mimetype` must be the first member and stored uncompressed. Readers
    /// that check this refuse the file outright, and the check is invisible in
    /// any test that only round-trips through our own parser.
    #[test]
    fn the_mimetype_is_first_and_stored() {
        let bytes = write("Book", None, &chapters()).expect("a small book fits a zip");
        assert!(
            bytes[30..].starts_with(b"mimetypeapplication/epub+zip"),
            "mimetype must be the first member, named and stored with no extras"
        );
        // Offset 8 of a local header is the compression method. 0 is stored.
        assert_eq!(u16::from_le_bytes([bytes[8], bytes[9]]), 0);
        let archive = Archive::open(&bytes).expect("a readable archive");
        assert_eq!(
            archive.read("mimetype").as_deref(),
            Ok(&b"application/epub+zip"[..])
        );
    }

    /// A book with no author must not claim one, and must still parse.
    #[test]
    fn an_author_is_left_out_rather_than_left_empty() {
        let bytes = write("Book", None, &chapters()).expect("a small book fits a zip");
        let document = parse(&bytes).expect("what we wrote must parse");
        assert_eq!(document.author, None);
    }

    #[test]
    fn a_title_that_is_all_punctuation_still_gets_an_identifier() {
        assert_eq!(slug("Moon: Past & Future"), "moon-past-future");
        assert_eq!(slug("???"), "book");
        assert_eq!(slug(""), "book");
    }

    /// Prose arrives as plain text, so blank lines are the only paragraph
    /// mark there is, and a single newline inside a paragraph is a wrap.
    #[test]
    fn blank_lines_separate_paragraphs_and_single_ones_do_not() {
        assert_eq!(
            paragraphs("one\nstill one\r\n\r\ntwo\n\n\n\nthree\n"),
            ["one still one", "two", "three"]
        );
        assert!(paragraphs("   \n\n  ").is_empty());
    }
}
