//! Reading HTML as a document.
//!
//! # Why not [`kobo_html::to_text`]
//!
//! That function exists for a Hacker News comment: a short fragment where the
//! only structure worth keeping is where the paragraphs are. It caps its
//! output at eight kilobytes and flattens everything else, and both are right
//! for a comment.
//!
//! A book is neither short nor flat. A chapter of a book is a heading and the
//! prose under it, and losing the heading loses the chapter, which is what
//! the table of contents is made of and what "next chapter" moves between. So
//! this is a second scanner over the same syntax, keeping the part the other
//! one throws away, and sharing the entity table and the attribute reader so
//! that the two cannot disagree about what `&rsquo;` is.
//!
//! # What it is not
//!
//! Not a compliant HTML parser. There is no tree, no implied end tags, no
//! error recovery algorithm, no `<table>` reconstruction. It is a scan over
//! the tags looking for the dozen elements that change what a run of text
//! *is*, and everything else is stripped and its contents kept. That is
//! enough for EPUB (which is XHTML, and generated by a tool) and enough for
//! a saved web page, and it cannot get stuck, recurse or allocate a tree.

use kobo_html::{attribute, decode_entities, element_name, skip_element};

use crate::{
    Block, BlockStyle, Builder, Document, InlineSpan, InlineStyle, RichBlock, TextAlignment,
    MAX_BLOCK_TEXT,
};

/// Elements whose contents are instructions rather than words.
const OPAQUE: [&str; 4] = ["script", "style", "svg", "iframe"];

/// Reads an HTML document.
#[must_use]
pub fn parse(source: &str) -> Document {
    parse_with_css(source, "")
}

/// Reads HTML with a bounded safe subset of publisher CSS.
#[must_use]
pub fn parse_with_css(source: &str, external_css: &str) -> Document {
    let mut take = external_css.len().min(MAX_CSS_BYTES);
    while !external_css.is_char_boundary(take) {
        take -= 1;
    }
    let mut css = external_css[..take].to_owned();
    css.push_str(&embedded_styles(source));
    let mut state = State::new(StyleSheet::parse(&css));
    let mut rest = source;
    while let Some(at) = rest.find('<') {
        state.words(&rest[..at]);
        let tail = &rest[at..];

        // A comment or a CDATA section may contain a `>` that does not end it.
        // Searching for the plain `>` first would cut inside one and spill the
        // remainder onto the panel.
        if let Some(after) = skip_bracketed(tail) {
            rest = after;
            continue;
        }

        let Some(end) = tail.find('>') else {
            // A `<` that never closes is not a tag. It is the character it is,
            // and reading it as an unterminated tag would silently drop
            // everything after it.
            state.words(tail);
            rest = "";
            break;
        };
        let inside = &tail[1..end];
        rest = &tail[end + 1..];

        let name = element_name(inside);
        let closing = inside.starts_with('/');
        if !closing && OPAQUE.contains(&name.as_str()) {
            rest = skip_element(rest, &name);
            continue;
        }
        if closing {
            state.close(&name);
        } else {
            state.open(&name, inside);
        }
    }
    state.words(rest);
    state.finish()
}

const MAX_CSS_BYTES: usize = 256 * 1024;
const MAX_CSS_RULES: usize = 4_096;

/// Skips a comment, a doctype or a CDATA section, if `tail` begins with one.
pub(crate) fn skip_bracketed(tail: &str) -> Option<&str> {
    for (opens, closes) in [("<!--", "-->"), ("<![CDATA[", "]]>")] {
        if let Some(body) = tail.strip_prefix(opens) {
            // An unterminated comment takes the rest of the file. That is the
            // safe direction: the alternative is drawing markup somebody left
            // half-written.
            return Some(
                body.find(closes)
                    .map_or("", |at| &body[at + closes.len()..]),
            );
        }
    }
    None
}

struct State {
    builder: Builder,
    text: String,
    spans: Vec<InlineSpan>,
    inline: InlineStyle,
    inline_stack: Vec<(String, InlineStyle)>,
    block_style: BlockStyle,
    block_stack: Vec<(String, BlockStyle)>,
    stylesheet: StyleSheet,
    /// The link being read: where it points, and how much text had been
    /// collected when it opened, so its own words can be taken back out.
    link: Option<(String, usize)>,
    /// How many block quotations deep the scan is. See `markdown` for why this
    /// is a count.
    quoted: usize,
    /// How many `<pre>` elements deep the scan is.
    ///
    /// Inside one, the line breaks are the content and no tag rearranges
    /// anything, so the whole of it is collected as written.
    pre: usize,
    /// Whether each open list is numbered, innermost last.
    lists: Vec<bool>,
    heading: Option<u8>,
    item: bool,
    /// Whether the words being collected are the document's title rather than
    /// something to draw.
    titling: bool,
}

impl State {
    fn new(stylesheet: StyleSheet) -> Self {
        Self {
            builder: Builder::new(),
            link: None,
            text: String::new(),
            spans: Vec::new(),
            inline: InlineStyle::default(),
            inline_stack: Vec::new(),
            block_style: BlockStyle::default(),
            block_stack: Vec::new(),
            stylesheet,
            quoted: 0,
            pre: 0,
            lists: Vec::new(),
            heading: None,
            item: false,
            titling: false,
        }
    }

    /// Adds a run of literal text.
    fn words(&mut self, text: &str) {
        if text.is_empty() {
            // Two adjacent tags, which is most of an EPUB.
            return;
        }
        // A document with no block-level tags at all is one paragraph as long
        // as the file. The block ceiling would cut it on the way out, but this
        // stops the buffer growing past it in the first place.
        if self.text.len() > MAX_BLOCK_TEXT {
            return;
        }
        let decoded = decode_entities(text);
        self.push_span(&decoded);
        if self.pre > 0 {
            // Control characters have no drawing, and the preformatted path
            // does not collapse them away. Tabs and newlines stay: both are
            // the reason this block is preformatted.
            self.text.extend(
                decoded
                    .chars()
                    .filter(|c| *c == '\n' || *c == '\t' || !c.is_control()),
            );
        } else {
            self.text.push_str(&decoded);
        }
    }

    fn push_span(&mut self, text: &str) {
        if text.is_empty() {
            return;
        }
        if let Some(last) = self
            .spans
            .last_mut()
            .filter(|last| last.style == self.inline)
        {
            last.text.push_str(text);
        } else {
            self.spans.push(InlineSpan {
                text: text.to_owned(),
                style: self.inline,
            });
        }
    }

    #[allow(clippy::too_many_lines)]
    fn open(&mut self, name: &str, inside: &str) {
        // Inside a `<pre>`, nothing but its own end tag changes anything. A
        // listing full of `<` is a listing, and re-flowing it on a stray tag
        // would lose the shape that is the whole point of the element.
        if self.pre > 0 {
            if name == "br" {
                self.text.push('\n');
            }
            return;
        }
        // Noted before the element is interpreted, because whatever this
        // element becomes is where the name points. A name on an element that
        // turns out to say nothing lands on the block after it, which is the
        // next thing a reader sent there would actually read.
        if let Some(id) = attribute(inside, "id") {
            self.builder.mark_anchor(&decode_entities(id));
        }
        if name == "img" {
            // Emitted where it stands, so a picture keeps its place among the
            // paragraphs. The source is left exactly as the book wrote it --
            // resolving it against the file it came from needs to know what
            // that file was, which only the format assembling the book does.
            if let Some(source) = attribute(inside, "src") {
                self.flush();
                let alt = attribute(inside, "alt")
                    .map(decode_entities)
                    .unwrap_or_default();
                self.builder.push(Block::Picture {
                    name: decode_entities(source),
                    alt,
                });
            }
            return;
        }
        if name == "a" {
            // Where the words of the link start, so they can be taken back
            // out when it closes: a link's own text is what a reader taps,
            // and the paragraph around it is not.
            if let Some(href) = attribute(inside, "href") {
                self.link = Some((decode_entities(href), self.text.len()));
            }
            return;
        }
        if matches!(
            name,
            "strong" | "b" | "em" | "i" | "u" | "sup" | "sub" | "span" | "small" | "mark"
        ) {
            self.inline_stack.push((name.to_owned(), self.inline));
            match name {
                "strong" | "b" => self.inline.strong = true,
                "em" | "i" => self.inline.emphasis = true,
                "u" => self.inline.underline = true,
                "sup" => self.inline.superscript = true,
                "sub" => self.inline.subscript = true,
                _ => {}
            }
            let declarations = self.stylesheet.declarations_for(name, inside);
            apply_inline_style(&mut self.inline, Some(&declarations));
            return;
        }
        match name {
            // A `<br>` is a soft break. One column, and the paginator wraps:
            // honouring it would give a ragged short line in the middle of a
            // paragraph.
            "br" => self.text.push(' '),
            // A picture cannot be drawn inside a run of text, so what it was
            // described as is the only part that can survive. An `<img>` with
            // no description says nothing, and brackets around nothing would
            // be worse than silence.
            "img" | "image" => {
                if let Some(alt) = attribute(inside, "alt").filter(|alt| !alt.trim().is_empty()) {
                    self.text.push_str(" [");
                    self.text.push_str(&decode_entities(alt));
                    self.text.push_str("] ");
                }
            }
            "hr" => {
                self.flush();
                self.builder.push(Block::Rule);
            }
            "title" => {
                self.flush();
                self.titling = true;
            }
            "meta" => self.read_meta(inside),
            "blockquote" | "q" => {
                self.flush();
                self.quoted += 1;
            }
            "pre" => {
                self.flush();
                self.pre += 1;
            }
            "ul" | "menu" | "dl" => {
                self.flush();
                self.lists.push(false);
            }
            "ol" => {
                self.flush();
                self.lists.push(true);
            }
            "li" | "dd" => {
                self.flush();
                self.item = true;
            }
            // A cell is not a paragraph of its own; a row is. Running the
            // cells together with a mark that does not occur inside one keeps
            // the row readable in a single column.
            "td" | "th" => {
                if !self.text.trim_end().is_empty() {
                    self.text.push_str(" \u{2014} ");
                }
            }
            _ => {
                if let Some(level) = heading_level(name) {
                    self.flush();
                    let declarations = self.stylesheet.declarations_for(name, inside);
                    let parent = self.block_style.clone();
                    self.block_stack.push((name.to_owned(), parent.clone()));
                    self.block_style = block_style_inheriting(&parent, &declarations);
                    self.inline_stack.push((name.to_owned(), self.inline));
                    apply_inline_style(&mut self.inline, Some(&declarations));
                    self.heading = Some(level);
                } else if breaks_a_block(name) {
                    self.flush();
                    let declarations = self.stylesheet.declarations_for(name, inside);
                    let parent = self.block_style.clone();
                    self.block_stack.push((name.to_owned(), parent.clone()));
                    self.block_style = block_style_inheriting(&parent, &declarations);
                    self.inline_stack.push((name.to_owned(), self.inline));
                    apply_inline_style(&mut self.inline, Some(&declarations));
                }
            }
        }
    }

    fn close(&mut self, name: &str) {
        if self.pre > 0 && name != "pre" {
            return;
        }
        if name == "a" {
            if let Some((target, from)) = self.link.take() {
                let words = self.text.get(from..).unwrap_or_default().to_owned();
                self.builder.record_link(&words, &target);
            }
            return;
        }
        if let Some(at) = self.inline_stack.iter().rposition(|(open, _)| open == name) {
            if heading_level(name).is_some() || breaks_a_block(name) {
                self.flush();
            }
            let (_, style) = self.inline_stack.remove(at);
            self.inline = style;
            if let Some(at) = self.block_stack.iter().rposition(|(open, _)| open == name) {
                let (_, style) = self.block_stack.remove(at);
                self.block_style = style;
            }
            return;
        }
        match name {
            // Flushed before the depth changes, so the last paragraph of a
            // quotation is still part of it.
            "blockquote" | "q" => {
                self.flush();
                self.quoted = self.quoted.saturating_sub(1);
            }
            "pre" => {
                self.flush();
                self.pre = self.pre.saturating_sub(1);
            }
            "ul" | "ol" | "menu" | "dl" => {
                self.flush();
                self.lists.pop();
            }
            "title" => self.flush(),
            _ => {
                if heading_level(name).is_some() || breaks_a_block(name) {
                    self.flush();
                }
            }
        }
    }

    /// Reads what a `<meta>` says the document is.
    fn read_meta(&mut self, inside: &str) {
        let Some(name) = attribute(inside, "name")
            .or_else(|| attribute(inside, "property"))
            .map(str::to_ascii_lowercase)
        else {
            return;
        };
        let Some(content) = attribute(inside, "content") else {
            return;
        };
        let content = decode_entities(content);
        match name.as_str() {
            "author" | "dc.creator" | "citation_author" | "article:author" => {
                self.builder.set_author(&content);
            }
            "og:title" | "dc.title" | "citation_title" => self.builder.set_title(&content),
            _ => {}
        }
    }

    fn flush(&mut self) {
        let text = std::mem::take(&mut self.text);
        let spans = normalise_spans(std::mem::take(&mut self.spans));
        let style = self.block_style.clone();
        let heading = self.heading.take();
        let item = std::mem::replace(&mut self.item, false);
        if std::mem::replace(&mut self.titling, false) {
            self.builder.set_title(&text);
            return;
        }
        if self.pre > 0 {
            self.builder
                .push_rich(Block::Preformatted(text), RichBlock { spans, style });
            return;
        }
        if text.trim().is_empty() {
            return;
        }
        if let Some(level) = heading {
            // A page with no `<title>` is usually still named by the one
            // heading at the top of it.
            if level == 1 {
                self.builder.set_title(&text);
            }
            self.builder
                .push_rich(Block::Heading { level, text }, RichBlock { spans, style });
        } else if item {
            let ordered = self.lists.last().copied().unwrap_or(false);
            self.builder
                .push_rich(Block::Item { ordered, text }, RichBlock { spans, style });
        } else if self.quoted > 0 {
            self.builder
                .push_rich(Block::Quote(text), RichBlock { spans, style });
        } else {
            self.builder
                .push_rich(Block::Paragraph(text), RichBlock { spans, style });
        }
    }

    fn finish(mut self) -> Document {
        self.flush();
        self.builder.finish()
    }
}

#[derive(Clone, Debug, Default)]
struct StyleSheet {
    rules: Vec<CssRule>,
}

#[derive(Clone, Debug)]
struct CssRule {
    selector: String,
    declarations: String,
    specificity: u8,
    order: usize,
}

fn embedded_styles(source: &str) -> String {
    let lower = source.to_ascii_lowercase();
    let mut out = String::new();
    let mut at = 0usize;
    while out.len() < MAX_CSS_BYTES {
        let Some(open) = lower[at..].find("<style") else {
            break;
        };
        let open = at + open;
        let Some(tag_end) = lower[open..].find('>') else {
            break;
        };
        let body = open + tag_end + 1;
        let Some(close) = lower[body..].find("</style") else {
            break;
        };
        let close = body + close;
        let content = &source[body..close];
        let mut take = content.len().min(MAX_CSS_BYTES.saturating_sub(out.len()));
        while !content.is_char_boundary(take) {
            take -= 1;
        }
        out.push_str(&content[..take]);
        at = close + "</style".len();
    }
    out
}

impl StyleSheet {
    fn parse(css: &str) -> Self {
        let mut rules = Vec::new();
        let mut rest = css;
        while rules.len() < MAX_CSS_RULES {
            let Some(open) = rest.find('{') else { break };
            let selectors = rest[..open].trim();
            let tail = &rest[open + 1..];
            let Some(close) = tail.find('}') else { break };
            let body = tail[..close].trim();
            rest = &tail[close + 1..];
            if selectors.starts_with('@') || body.is_empty() {
                continue;
            }
            for selector in selectors.split(',') {
                let selector = selector.trim().to_ascii_lowercase();
                if selector.is_empty()
                    || selector.contains([' ', '>', '+', '~', '[', ':', '*'])
                    || rules.len() >= MAX_CSS_RULES
                {
                    continue;
                }
                let specificity = u8::from(selector.contains('#')) * 100
                    + u8::try_from(selector.matches('.').count())
                        .unwrap_or(9)
                        .min(9)
                        * 10
                    + u8::from(!selector.starts_with(['.', '#']));
                rules.push(CssRule {
                    selector,
                    declarations: body.to_owned(),
                    specificity,
                    order: rules.len(),
                });
            }
        }
        Self { rules }
    }

    fn declarations_for(&self, name: &str, inside: &str) -> String {
        let classes = attribute(inside, "class").unwrap_or_default();
        let id = attribute(inside, "id").unwrap_or_default();
        let mut matched: Vec<&CssRule> = self
            .rules
            .iter()
            .filter(|rule| selector_matches(&rule.selector, name, id, classes))
            .collect();
        matched.sort_by_key(|rule| (rule.specificity, rule.order));
        let mut result = String::new();
        for rule in matched {
            result.push_str(&rule.declarations);
            result.push(';');
        }
        if let Some(inline) = attribute(inside, "style") {
            result.push_str(inline);
        }
        result
    }
}

fn selector_matches(selector: &str, name: &str, id: &str, classes: &str) -> bool {
    let tag_end = selector.find(['.', '#']).unwrap_or(selector.len());
    let tag = &selector[..tag_end];
    if !tag.is_empty() && !tag.eq_ignore_ascii_case(name) {
        return false;
    }
    let class_words: Vec<&str> = classes.split_whitespace().collect();
    let mut rest = &selector[tag_end..];
    while !rest.is_empty() {
        let marker = rest.as_bytes()[0];
        rest = &rest[1..];
        let end = rest.find(['.', '#']).unwrap_or(rest.len());
        let value = &rest[..end];
        let matches = match marker {
            b'.' => class_words
                .iter()
                .any(|class| class.eq_ignore_ascii_case(value)),
            b'#' => id.eq_ignore_ascii_case(value),
            _ => false,
        };
        if !matches {
            return false;
        }
        rest = &rest[end..];
    }
    true
}

fn normalise_spans(spans: Vec<InlineSpan>) -> Vec<InlineSpan> {
    let mut out: Vec<InlineSpan> = Vec::new();
    let mut pending_space = false;
    for span in spans {
        let mut text = String::new();
        for character in span.text.chars() {
            if character.is_whitespace() {
                pending_space = !out.is_empty() || !text.is_empty();
                continue;
            }
            if pending_space {
                text.push(' ');
                pending_space = false;
            }
            if !character.is_control() {
                text.push(character);
            }
        }
        if text.is_empty() {
            continue;
        }
        if let Some(last) = out.last_mut().filter(|last| last.style == span.style) {
            last.text.push_str(&text);
        } else {
            out.push(InlineSpan {
                text,
                style: span.style,
            });
        }
    }
    out
}

fn declarations(style: Option<&str>) -> impl Iterator<Item = (&str, &str)> {
    style.into_iter().flat_map(|style| {
        style.split(';').filter_map(|declaration| {
            let (name, value) = declaration.split_once(':')?;
            Some((name.trim(), value.trim()))
        })
    })
}

fn apply_inline_style(style: &mut InlineStyle, source: Option<&str>) {
    for (name, value) in declarations(source) {
        match name.to_ascii_lowercase().as_str() {
            "font-weight"
                if value.eq_ignore_ascii_case("bold")
                    || value.parse::<u16>().is_ok_and(|weight| weight >= 600) =>
            {
                style.strong = true;
            }
            "font-style"
                if value.eq_ignore_ascii_case("italic")
                    || value.eq_ignore_ascii_case("oblique") =>
            {
                style.emphasis = true;
            }
            "text-decoration"
                if value
                    .split_whitespace()
                    .any(|word| word.eq_ignore_ascii_case("underline")) =>
            {
                style.underline = true;
            }
            "vertical-align" if value.eq_ignore_ascii_case("super") => style.superscript = true,
            "vertical-align" if value.eq_ignore_ascii_case("sub") => style.subscript = true,
            _ => {}
        }
    }
}

fn block_style_inheriting(parent: &BlockStyle, source: &str) -> BlockStyle {
    let mut style = BlockStyle {
        alignment: parent.alignment,
        line_height_percent: parent.line_height_percent,
        font_family: parent.font_family.clone(),
        ..BlockStyle::default()
    };
    for (name, value) in declarations(Some(source)) {
        match name.to_ascii_lowercase().as_str() {
            "text-align" => {
                style.alignment = match value.to_ascii_lowercase().as_str() {
                    "center" => TextAlignment::Center,
                    "right" | "end" => TextAlignment::End,
                    "justify" => TextAlignment::Justify,
                    _ => TextAlignment::Start,
                };
            }
            "line-height" => {
                if let Some(percent) = percent(value) {
                    style.line_height_percent = percent.clamp(80, 250);
                }
            }
            "margin-top" => style.margin_before_em = em_hundredths(value).unwrap_or(0),
            "margin-bottom" => style.margin_after_em = em_hundredths(value).unwrap_or(0),
            "text-indent" => {
                style.first_line_indent_em = em_hundredths(value)
                    .and_then(|value| i16::try_from(value).ok())
                    .unwrap_or(0);
            }
            "font-family" => {
                let family = value
                    .split(',')
                    .next()
                    .unwrap_or_default()
                    .trim_matches([' ', '\'', '"']);
                if !family.is_empty() && family.len() <= 128 {
                    style.font_family = Some(family.to_owned());
                }
            }
            "page-break-before" | "break-before"
                if value.eq_ignore_ascii_case("always") || value.eq_ignore_ascii_case("page") =>
            {
                style.page_break_before = true;
            }
            "page-break-after" | "break-after"
                if value.eq_ignore_ascii_case("always") || value.eq_ignore_ascii_case("page") =>
            {
                style.page_break_after = true;
            }
            _ => {}
        }
    }
    style
}

#[allow(clippy::cast_possible_truncation)]
fn percent(value: &str) -> Option<u16> {
    if let Some(value) = value.strip_suffix('%') {
        return value.trim().parse().ok();
    }
    let ratio = value.parse::<f32>().ok()?;
    u16::try_from((ratio * 100.0).round() as i32).ok()
}

#[allow(clippy::cast_possible_truncation)]
fn em_hundredths(value: &str) -> Option<u16> {
    let value = value.trim().strip_suffix("em")?.trim();
    let em = value.parse::<f32>().ok()?;
    if !(0.0..=20.0).contains(&em) {
        return None;
    }
    u16::try_from((em * 100.0).round() as i32).ok()
}

fn heading_level(name: &str) -> Option<u8> {
    match name {
        "h1" => Some(1),
        "h2" => Some(2),
        "h3" => Some(3),
        "h4" => Some(4),
        "h5" => Some(5),
        "h6" => Some(6),
        _ => None,
    }
}

/// Whether this element separates what came before it from what follows.
///
/// The list is generous on purpose. Mistaking a container for a paragraph
/// break costs a paragraph break that was going to be there anyway once the
/// contents were laid out; missing one runs a heading into the sentence after
/// it, which is visible on the page.
fn breaks_a_block(name: &str) -> bool {
    matches!(
        name,
        "p" | "div"
            | "section"
            | "article"
            | "header"
            | "footer"
            | "main"
            | "aside"
            | "nav"
            | "body"
            | "html"
            | "head"
            | "hgroup"
            | "figure"
            | "figcaption"
            | "caption"
            | "address"
            | "center"
            | "table"
            | "thead"
            | "tbody"
            | "tfoot"
            | "tr"
            | "dt"
            | "form"
            | "fieldset"
            | "details"
            | "summary"
            | "noscript"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_heading_survives_as_a_heading() {
        // This is the whole reason for a second scanner. `to_text` would give
        // back a paragraph, and the chapter boundary would be gone.
        let document = parse("<h2>Chapter One</h2><p>It began badly.</p>");
        assert_eq!(
            document.blocks,
            vec![
                Block::Heading {
                    level: 2,
                    text: "Chapter One".to_owned()
                },
                Block::Paragraph("It began badly.".to_owned()),
            ]
        );
    }

    #[test]
    fn inline_structure_and_safe_publisher_css_survive_parsing() {
        let document = parse(
            r#"<style>
                p.lead { text-align: center; line-height: 140%; margin-bottom: 0.5em; }
                .accent { font-style: italic; text-decoration: underline; }
               </style>
               <p class="lead">Before <strong>bold <span class="accent">both</span></strong>.</p>"#,
        );
        assert_eq!(document.blocks[0].text(), Some("Before bold both."));
        let rich = document.rich.get(&0).expect("rich paragraph");
        assert_eq!(rich.style.alignment, TextAlignment::Center);
        assert_eq!(rich.style.line_height_percent, 140);
        assert_eq!(rich.style.margin_after_em, 50);
        assert_eq!(
            rich.spans
                .iter()
                .map(|span| span.text.as_str())
                .collect::<String>(),
            "Before bold both."
        );
        let both = rich
            .spans
            .iter()
            .find(|span| span.text.contains("both"))
            .expect("styled run");
        assert!(both.style.strong);
        assert!(both.style.emphasis);
        assert!(both.style.underline);
    }

    #[test]
    fn unsupported_css_cannot_escape_the_bounded_flow() {
        let document = parse_with_css(
            r#"<p class="moved">Words stay readable.</p>"#,
            ".moved { position: fixed; left: -999999px; color: transparent; text-align: right; }",
        );
        assert_eq!(document.blocks[0].text(), Some("Words stay readable."));
        assert_eq!(
            document
                .rich
                .get(&0)
                .expect("supported style")
                .style
                .alignment,
            TextAlignment::End
        );
    }

    #[test]
    fn tag_per_character_styling_is_bounded_without_losing_words() {
        let mut source = String::from("<p>");
        for index in 0..400 {
            if index % 2 == 0 {
                source.push_str("<b>x</b>");
            } else {
                source.push_str("<i>y</i>");
            }
        }
        source.push_str("</p>");
        let document = parse(&source);
        let text = document.blocks[0].text().expect("paragraph");
        let rich = document.rich.get(&0).expect("rich paragraph");
        assert_eq!(text.len(), 400);
        assert_eq!(
            rich.spans.iter().map(|span| span.text.len()).sum::<usize>(),
            400
        );
        assert!(rich.spans.len() <= crate::MAX_RICH_SPANS);
    }

    #[test]
    fn inherited_body_typography_reaches_ordinary_paragraphs() {
        let document = parse_with_css(
            "<body><p>Inherited prose.</p></body>",
            "body { font-family: Publisher Serif; line-height: 135%; text-align: justify; }",
        );
        let style = &document.rich.get(&0).expect("publisher style").style;
        assert_eq!(style.font_family.as_deref(), Some("Publisher Serif"));
        assert_eq!(style.line_height_percent, 135);
        assert_eq!(style.alignment, TextAlignment::Justify);
    }

    #[test]
    fn a_heading_does_not_run_into_the_sentence_after_it() {
        // No closing tag anywhere, which is what a saved web page looks like.
        let document = parse("<h1>Title<p>Words.");
        assert_eq!(document.blocks.len(), 2);
        assert_eq!(document.blocks[0].text(), Some("Title"));
    }

    #[test]
    fn a_document_is_named_by_its_title_element() {
        let document = parse("<html><head><title>A Book</title></head><body><p>Hi</p></body>");
        assert_eq!(document.title.as_deref(), Some("A Book"));
        assert_eq!(
            document.blocks,
            vec![Block::Paragraph("Hi".to_owned())],
            "the title was drawn as content"
        );
    }

    #[test]
    fn a_meta_author_is_read() {
        let document = parse("<meta name=\"author\" content=\"A Person\"><p>Words.");
        assert_eq!(document.author.as_deref(), Some("A Person"));
    }

    #[test]
    fn a_script_is_never_read_as_prose() {
        let document = parse("<p>Before.<script>var a = 1 < 2;</script><p>After.");
        assert_eq!(
            document.blocks,
            vec![
                Block::Paragraph("Before.".to_owned()),
                Block::Paragraph("After.".to_owned()),
            ]
        );
    }

    #[test]
    fn a_comment_containing_an_angle_bracket_does_not_spill() {
        // Searching for the next `>` cuts inside the comment and puts the rest
        // of it on the page.
        let document = parse("<p>Before.<!-- a > b and <p>fake --><p>After.");
        assert_eq!(
            document.blocks,
            vec![
                Block::Paragraph("Before.".to_owned()),
                Block::Paragraph("After.".to_owned()),
            ]
        );
    }

    #[test]
    fn a_cdata_section_is_not_read() {
        let document = parse("<p>Before.<![CDATA[ <p>not a tag</p> ]]><p>After.");
        assert_eq!(document.blocks.len(), 2);
    }

    #[test]
    fn preformatted_text_keeps_its_line_breaks_and_its_angle_brackets() {
        let document = parse("<pre>fn main() {\n    if a &lt; b {}\n}</pre>");
        let Block::Preformatted(text) = &document.blocks[0] else {
            panic!("a listing was re-flowed: {:?}", document.blocks[0]);
        };
        assert_eq!(text.lines().count(), 3);
        assert!(
            text.contains("a < b"),
            "the entity was not decoded: {text:?}"
        );
        assert!(text.contains("    if"), "the indent was lost: {text:?}");
    }

    #[test]
    fn a_stray_tag_inside_a_listing_does_not_break_it_up() {
        let document = parse("<pre>a\n<div>\nb</pre>");
        assert_eq!(document.blocks.len(), 1, "{:?}", document.blocks);
    }

    #[test]
    fn a_quotation_ends_where_it_closes() {
        let document = parse("<blockquote><p>Quoted.</p></blockquote><p>Plain.</p>");
        assert_eq!(
            document.blocks,
            vec![
                Block::Quote("Quoted.".to_owned()),
                Block::Paragraph("Plain.".to_owned()),
            ]
        );
    }

    #[test]
    fn the_last_paragraph_of_a_quotation_is_still_part_of_it() {
        // Flushing after the depth changed would let it out as prose.
        let document = parse("<blockquote>Only this.</blockquote>");
        assert_eq!(document.blocks, vec![Block::Quote("Only this.".to_owned())]);
    }

    #[test]
    fn a_list_knows_whether_it_is_numbered() {
        let document = parse("<ol><li>first</li><li>second</li></ol><ul><li>a</li></ul>");
        assert_eq!(
            document.blocks,
            vec![
                Block::Item {
                    ordered: true,
                    text: "first".to_owned()
                },
                Block::Item {
                    ordered: true,
                    text: "second".to_owned()
                },
                Block::Item {
                    ordered: false,
                    text: "a".to_owned()
                },
            ]
        );
    }

    #[test]
    fn a_link_keeps_its_words_and_loses_its_destination() {
        let document = parse("<p>See <a href=\"https://example.invalid/x\">the manual</a>.</p>");
        assert_eq!(
            document.blocks,
            vec![Block::Paragraph("See the manual.".to_owned())]
        );
    }

    #[test]
    fn a_picture_becomes_something_that_can_be_drawn_rather_than_described() {
        // This used to fold the description into the sentence as "[a cat]",
        // which was the best a reader could do when a picture could not be
        // drawn at all. It can be now, so the picture is a block of its own
        // and keeps its description for the case where it still cannot --
        // which splits a paragraph an illustration was sitting inside. That
        // is the right way round for a book: an illustration is nearly always
        // its own paragraph already, and one genuinely mid-sentence is
        // decorative.
        let document = parse("<p>Before <img src=\"a.png\" alt=\"a cat\"> after.</p>");
        assert_eq!(
            document.blocks,
            vec![
                Block::Paragraph("Before".to_owned()),
                Block::Picture {
                    name: "a.png".to_owned(),
                    alt: "a cat".to_owned()
                },
                Block::Paragraph("after.".to_owned()),
            ]
        );
    }

    #[test]
    fn a_picture_with_no_description_still_has_somewhere_to_be_drawn() {
        // No description is not nothing: the picture is still there, and a
        // book whose plates carry no alt text is the ordinary case rather
        // than the exception.
        let document = parse("<p>Before <img src=\"a.png\" alt=\"\"> after.</p>");
        assert_eq!(
            document.blocks,
            vec![
                Block::Paragraph("Before".to_owned()),
                Block::Picture {
                    name: "a.png".to_owned(),
                    alt: String::new()
                },
                Block::Paragraph("after.".to_owned()),
            ]
        );
    }

    #[test]
    fn a_picture_with_no_source_is_not_a_picture() {
        let document = parse("<p>Before <img alt=\"a cat\"> after.</p>");
        assert_eq!(
            document.blocks,
            vec![Block::Paragraph("Before after.".to_owned())]
        );
    }

    #[test]
    fn a_soft_break_does_not_start_a_new_paragraph() {
        let document = parse("<p>One line<br>and its continuation.</p>");
        assert_eq!(
            document.blocks,
            vec![Block::Paragraph(
                "One line and its continuation.".to_owned()
            )]
        );
    }

    #[test]
    fn a_table_row_becomes_one_readable_line() {
        let document = parse("<table><tr><td>a</td><td>b</td></tr><tr><td>1</td><td>2</td></tr>");
        assert_eq!(
            document.blocks,
            vec![
                Block::Paragraph("a \u{2014} b".to_owned()),
                Block::Paragraph("1 \u{2014} 2".to_owned()),
            ]
        );
    }

    #[test]
    fn the_indentation_of_the_source_is_not_the_indentation_of_the_prose() {
        let document = parse("<p>\n    Words\n    and more words.\n</p>");
        assert_eq!(
            document.blocks,
            vec![Block::Paragraph("Words and more words.".to_owned())]
        );
    }

    #[test]
    fn an_unclosed_angle_bracket_is_a_character_and_not_the_end_of_the_document() {
        let document = parse("<p>a < b and that is all");
        assert_eq!(document.blocks[0].text(), Some("a < b and that is all"));
    }

    #[test]
    fn nothing_here_panics_on_anything() {
        for source in [
            "",
            "<",
            "<<<<<",
            "<!--",
            "<![CDATA[",
            "</p></p></blockquote></ul></pre>",
            "<pre>",
            "<script>",
            &"<blockquote>".repeat(10_000),
            &"<ul>".repeat(10_000),
            &"<p>".repeat(10_000),
            &"&".repeat(10_000),
            &"\u{e9}".repeat(10_000),
        ] {
            let _ = parse(source);
        }
    }

    #[test]
    fn a_document_with_no_tags_at_all_is_still_bounded() {
        let document = parse(&"word ".repeat(200_000));
        assert!(document.truncated);
        assert!(document.blocks[0].text().unwrap_or_default().len() <= MAX_BLOCK_TEXT);
    }
}
