//! Reading HTML as a document.
//!
//! # Why not [`kobo_html::to_text`]
//!
//! That function exists for a Hacker News comment: a short fragment where the
//! only structure worth keeping is where the paragraphs are. It caps its
//! output at eight kilobytes and flattens everything else, and both are right
//! for a comment.
//!
//! A book is neither short nor flat. A chapter of a book is a heading and the
//! prose under it, and losing the heading loses the chapter, which is what
//! the table of contents is made of and what "next chapter" moves between. So
//! this is a second scanner over the same syntax, keeping the part the other
//! one throws away, and sharing the entity table and the attribute reader so
//! that the two cannot disagree about what `&rsquo;` is.
//!
//! # What it is not
//!
//! Not a compliant HTML parser. There is no tree, no implied end tags, no
//! error recovery algorithm, no `<table>` reconstruction. It is a scan over
//! the tags looking for the dozen elements that change what a run of text
//! *is*, and everything else is stripped and its contents kept. That is
//! enough for EPUB (which is XHTML, and generated by a tool) and enough for
//! a saved web page, and it cannot get stuck, recurse or allocate a tree.

use kobo_html::{attribute, decode_entities, element_name, skip_element};

use crate::{Block, Builder, Document, MAX_BLOCK_TEXT};

/// Elements whose contents are instructions rather than words.
const OPAQUE: [&str; 4] = ["script", "style", "svg", "iframe"];

/// Reads an HTML document.
#[must_use]
pub fn parse(source: &str) -> Document {
    let mut state = State::new();
    let mut rest = source;
    while let Some(at) = rest.find('<') {
        state.words(&rest[..at]);
        let tail = &rest[at..];

        // A comment or a CDATA section may contain a `>` that does not end it.
        // Searching for the plain `>` first would cut inside one and spill the
        // remainder onto the panel.
        if let Some(after) = skip_bracketed(tail) {
            rest = after;
            continue;
        }

        let Some(end) = tail.find('>') else {
            // A `<` that never closes is not a tag. It is the character it is,
            // and reading it as an unterminated tag would silently drop
            // everything after it.
            state.words(tail);
            rest = "";
            break;
        };
        let inside = &tail[1..end];
        rest = &tail[end + 1..];

        let name = element_name(inside);
        let closing = inside.starts_with('/');
        if !closing && OPAQUE.contains(&name.as_str()) {
            rest = skip_element(rest, &name);
            continue;
        }
        if closing {
            state.close(&name);
        } else {
            state.open(&name, inside);
        }
    }
    state.words(rest);
    state.finish()
}

/// Skips a comment, a doctype or a CDATA section, if `tail` begins with one.
pub(crate) fn skip_bracketed(tail: &str) -> Option<&str> {
    for (opens, closes) in [("<!--", "-->"), ("<![CDATA[", "]]>")] {
        if let Some(body) = tail.strip_prefix(opens) {
            // An unterminated comment takes the rest of the file. That is the
            // safe direction: the alternative is drawing markup somebody left
            // half-written.
            return Some(
                body.find(closes)
                    .map_or("", |at| &body[at + closes.len()..]),
            );
        }
    }
    None
}

struct State {
    builder: Builder,
    text: String,
    /// How many block quotations deep the scan is. See `markdown` for why this
    /// is a count.
    quoted: usize,
    /// How many `<pre>` elements deep the scan is.
    ///
    /// Inside one, the line breaks are the content and no tag rearranges
    /// anything, so the whole of it is collected as written.
    pre: usize,
    /// Whether each open list is numbered, innermost last.
    lists: Vec<bool>,
    heading: Option<u8>,
    item: bool,
    /// Whether the words being collected are the document's title rather than
    /// something to draw.
    titling: bool,
}

impl State {
    fn new() -> Self {
        Self {
            builder: Builder::new(),
            text: String::new(),
            quoted: 0,
            pre: 0,
            lists: Vec::new(),
            heading: None,
            item: false,
            titling: false,
        }
    }

    /// Adds a run of literal text.
    fn words(&mut self, text: &str) {
        if text.is_empty() {
            // Two adjacent tags, which is most of an EPUB.
            return;
        }
        // A document with no block-level tags at all is one paragraph as long
        // as the file. The block ceiling would cut it on the way out, but this
        // stops the buffer growing past it in the first place.
        if self.text.len() > MAX_BLOCK_TEXT {
            return;
        }
        let decoded = decode_entities(text);
        if self.pre > 0 {
            // Control characters have no drawing, and the preformatted path
            // does not collapse them away. Tabs and newlines stay: both are
            // the reason this block is preformatted.
            self.text.extend(
                decoded
                    .chars()
                    .filter(|c| *c == '\n' || *c == '\t' || !c.is_control()),
            );
        } else {
            self.text.push_str(&decoded);
        }
    }

    fn open(&mut self, name: &str, inside: &str) {
        // Inside a `<pre>`, nothing but its own end tag changes anything. A
        // listing full of `<` is a listing, and re-flowing it on a stray tag
        // would lose the shape that is the whole point of the element.
        if self.pre > 0 {
            if name == "br" {
                self.text.push('\n');
            }
            return;
        }
        // Noted before the element is interpreted, because whatever this
        // element becomes is where the name points. A name on an element that
        // turns out to say nothing lands on the block after it, which is the
        // next thing a reader sent there would actually read.
        if let Some(id) = attribute(inside, "id") {
            self.builder.mark_anchor(&decode_entities(id));
        }
        match name {
            // A `<br>` is a soft break. One column, and the paginator wraps:
            // honouring it would give a ragged short line in the middle of a
            // paragraph.
            "br" => self.text.push(' '),
            // A picture cannot be drawn inside a run of text, so what it was
            // described as is the only part that can survive. An `<img>` with
            // no description says nothing, and brackets around nothing would
            // be worse than silence.
            "img" | "image" => {
                if let Some(alt) = attribute(inside, "alt").filter(|alt| !alt.trim().is_empty()) {
                    self.text.push_str(" [");
                    self.text.push_str(&decode_entities(alt));
                    self.text.push_str("] ");
                }
            }
            "hr" => {
                self.flush();
                self.builder.push(Block::Rule);
            }
            "title" => {
                self.flush();
                self.titling = true;
            }
            "meta" => self.read_meta(inside),
            "blockquote" | "q" => {
                self.flush();
                self.quoted += 1;
            }
            "pre" => {
                self.flush();
                self.pre += 1;
            }
            "ul" | "menu" | "dl" => {
                self.flush();
                self.lists.push(false);
            }
            "ol" => {
                self.flush();
                self.lists.push(true);
            }
            "li" | "dd" => {
                self.flush();
                self.item = true;
            }
            // A cell is not a paragraph of its own; a row is. Running the
            // cells together with a mark that does not occur inside one keeps
            // the row readable in a single column.
            "td" | "th" => {
                if !self.text.trim_end().is_empty() {
                    self.text.push_str(" \u{2014} ");
                }
            }
            _ => {
                if let Some(level) = heading_level(name) {
                    self.flush();
                    self.heading = Some(level);
                } else if breaks_a_block(name) {
                    self.flush();
                }
            }
        }
    }

    fn close(&mut self, name: &str) {
        if self.pre > 0 && name != "pre" {
            return;
        }
        match name {
            // Flushed before the depth changes, so the last paragraph of a
            // quotation is still part of it.
            "blockquote" | "q" => {
                self.flush();
                self.quoted = self.quoted.saturating_sub(1);
            }
            "pre" => {
                self.flush();
                self.pre = self.pre.saturating_sub(1);
            }
            "ul" | "ol" | "menu" | "dl" => {
                self.flush();
                self.lists.pop();
            }
            "title" => self.flush(),
            _ => {
                if heading_level(name).is_some() || breaks_a_block(name) {
                    self.flush();
                }
            }
        }
    }

    /// Reads what a `<meta>` says the document is.
    fn read_meta(&mut self, inside: &str) {
        let Some(name) = attribute(inside, "name")
            .or_else(|| attribute(inside, "property"))
            .map(str::to_ascii_lowercase)
        else {
            return;
        };
        let Some(content) = attribute(inside, "content") else {
            return;
        };
        let content = decode_entities(content);
        match name.as_str() {
            "author" | "dc.creator" | "citation_author" | "article:author" => {
                self.builder.set_author(&content);
            }
            "og:title" | "dc.title" | "citation_title" => self.builder.set_title(&content),
            _ => {}
        }
    }

    fn flush(&mut self) {
        let text = std::mem::take(&mut self.text);
        let heading = self.heading.take();
        let item = std::mem::replace(&mut self.item, false);
        if std::mem::replace(&mut self.titling, false) {
            self.builder.set_title(&text);
            return;
        }
        if self.pre > 0 {
            self.builder.push(Block::Preformatted(text));
            return;
        }
        if text.trim().is_empty() {
            return;
        }
        if let Some(level) = heading {
            // A page with no `<title>` is usually still named by the one
            // heading at the top of it.
            if level == 1 {
                self.builder.set_title(&text);
            }
            self.builder.push(Block::Heading { level, text });
        } else if item {
            let ordered = self.lists.last().copied().unwrap_or(false);
            self.builder.push(Block::Item { ordered, text });
        } else if self.quoted > 0 {
            self.builder.push(Block::Quote(text));
        } else {
            self.builder.push(Block::Paragraph(text));
        }
    }

    fn finish(mut self) -> Document {
        self.flush();
        self.builder.finish()
    }
}

fn heading_level(name: &str) -> Option<u8> {
    match name {
        "h1" => Some(1),
        "h2" => Some(2),
        "h3" => Some(3),
        "h4" => Some(4),
        "h5" => Some(5),
        "h6" => Some(6),
        _ => None,
    }
}

/// Whether this element separates what came before it from what follows.
///
/// The list is generous on purpose. Mistaking a container for a paragraph
/// break costs a paragraph break that was going to be there anyway once the
/// contents were laid out; missing one runs a heading into the sentence after
/// it, which is visible on the page.
fn breaks_a_block(name: &str) -> bool {
    matches!(
        name,
        "p" | "div"
            | "section"
            | "article"
            | "header"
            | "footer"
            | "main"
            | "aside"
            | "nav"
            | "body"
            | "html"
            | "head"
            | "hgroup"
            | "figure"
            | "figcaption"
            | "caption"
            | "address"
            | "center"
            | "table"
            | "thead"
            | "tbody"
            | "tfoot"
            | "tr"
            | "dt"
            | "form"
            | "fieldset"
            | "details"
            | "summary"
            | "noscript"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_heading_survives_as_a_heading() {
        // This is the whole reason for a second scanner. `to_text` would give
        // back a paragraph, and the chapter boundary would be gone.
        let document = parse("<h2>Chapter One</h2><p>It began badly.</p>");
        assert_eq!(
            document.blocks,
            vec![
                Block::Heading {
                    level: 2,
                    text: "Chapter One".to_owned()
                },
                Block::Paragraph("It began badly.".to_owned()),
            ]
        );
    }

    #[test]
    fn a_heading_does_not_run_into_the_sentence_after_it() {
        // No closing tag anywhere, which is what a saved web page looks like.
        let document = parse("<h1>Title<p>Words.");
        assert_eq!(document.blocks.len(), 2);
        assert_eq!(document.blocks[0].text(), Some("Title"));
    }

    #[test]
    fn a_document_is_named_by_its_title_element() {
        let document = parse("<html><head><title>A Book</title></head><body><p>Hi</p></body>");
        assert_eq!(document.title.as_deref(), Some("A Book"));
        assert_eq!(
            document.blocks,
            vec![Block::Paragraph("Hi".to_owned())],
            "the title was drawn as content"
        );
    }

    #[test]
    fn a_meta_author_is_read() {
        let document = parse("<meta name=\"author\" content=\"A Person\"><p>Words.");
        assert_eq!(document.author.as_deref(), Some("A Person"));
    }

    #[test]
    fn a_script_is_never_read_as_prose() {
        let document = parse("<p>Before.<script>var a = 1 < 2;</script><p>After.");
        assert_eq!(
            document.blocks,
            vec![
                Block::Paragraph("Before.".to_owned()),
                Block::Paragraph("After.".to_owned()),
            ]
        );
    }

    #[test]
    fn a_comment_containing_an_angle_bracket_does_not_spill() {
        // Searching for the next `>` cuts inside the comment and puts the rest
        // of it on the page.
        let document = parse("<p>Before.<!-- a > b and <p>fake --><p>After.");
        assert_eq!(
            document.blocks,
            vec![
                Block::Paragraph("Before.".to_owned()),
                Block::Paragraph("After.".to_owned()),
            ]
        );
    }

    #[test]
    fn a_cdata_section_is_not_read() {
        let document = parse("<p>Before.<![CDATA[ <p>not a tag</p> ]]><p>After.");
        assert_eq!(document.blocks.len(), 2);
    }

    #[test]
    fn preformatted_text_keeps_its_line_breaks_and_its_angle_brackets() {
        let document = parse("<pre>fn main() {\n    if a &lt; b {}\n}</pre>");
        let Block::Preformatted(text) = &document.blocks[0] else {
            panic!("a listing was re-flowed: {:?}", document.blocks[0]);
        };
        assert_eq!(text.lines().count(), 3);
        assert!(
            text.contains("a < b"),
            "the entity was not decoded: {text:?}"
        );
        assert!(text.contains("    if"), "the indent was lost: {text:?}");
    }

    #[test]
    fn a_stray_tag_inside_a_listing_does_not_break_it_up() {
        let document = parse("<pre>a\n<div>\nb</pre>");
        assert_eq!(document.blocks.len(), 1, "{:?}", document.blocks);
    }

    #[test]
    fn a_quotation_ends_where_it_closes() {
        let document = parse("<blockquote><p>Quoted.</p></blockquote><p>Plain.</p>");
        assert_eq!(
            document.blocks,
            vec![
                Block::Quote("Quoted.".to_owned()),
                Block::Paragraph("Plain.".to_owned()),
            ]
        );
    }

    #[test]
    fn the_last_paragraph_of_a_quotation_is_still_part_of_it() {
        // Flushing after the depth changed would let it out as prose.
        let document = parse("<blockquote>Only this.</blockquote>");
        assert_eq!(document.blocks, vec![Block::Quote("Only this.".to_owned())]);
    }

    #[test]
    fn a_list_knows_whether_it_is_numbered() {
        let document = parse("<ol><li>first</li><li>second</li></ol><ul><li>a</li></ul>");
        assert_eq!(
            document.blocks,
            vec![
                Block::Item {
                    ordered: true,
                    text: "first".to_owned()
                },
                Block::Item {
                    ordered: true,
                    text: "second".to_owned()
                },
                Block::Item {
                    ordered: false,
                    text: "a".to_owned()
                },
            ]
        );
    }

    #[test]
    fn a_link_keeps_its_words_and_loses_its_destination() {
        let document = parse("<p>See <a href=\"https://example.invalid/x\">the manual</a>.</p>");
        assert_eq!(
            document.blocks,
            vec![Block::Paragraph("See the manual.".to_owned())]
        );
    }

    #[test]
    fn a_picture_leaves_behind_what_it_was_described_as() {
        let document = parse("<p>Before <img src=\"a.png\" alt=\"a cat\"> after.</p>");
        assert_eq!(
            document.blocks,
            vec![Block::Paragraph("Before [a cat] after.".to_owned())]
        );
    }

    #[test]
    fn a_picture_with_no_description_says_nothing() {
        let document = parse("<p>Before <img src=\"a.png\" alt=\"\"> after.</p>");
        assert_eq!(
            document.blocks,
            vec![Block::Paragraph("Before after.".to_owned())]
        );
    }

    #[test]
    fn a_soft_break_does_not_start_a_new_paragraph() {
        let document = parse("<p>One line<br>and its continuation.</p>");
        assert_eq!(
            document.blocks,
            vec![Block::Paragraph(
                "One line and its continuation.".to_owned()
            )]
        );
    }

    #[test]
    fn a_table_row_becomes_one_readable_line() {
        let document = parse("<table><tr><td>a</td><td>b</td></tr><tr><td>1</td><td>2</td></tr>");
        assert_eq!(
            document.blocks,
            vec![
                Block::Paragraph("a \u{2014} b".to_owned()),
                Block::Paragraph("1 \u{2014} 2".to_owned()),
            ]
        );
    }

    #[test]
    fn the_indentation_of_the_source_is_not_the_indentation_of_the_prose() {
        let document = parse("<p>\n    Words\n    and more words.\n</p>");
        assert_eq!(
            document.blocks,
            vec![Block::Paragraph("Words and more words.".to_owned())]
        );
    }

    #[test]
    fn an_unclosed_angle_bracket_is_a_character_and_not_the_end_of_the_document() {
        let document = parse("<p>a < b and that is all");
        assert_eq!(document.blocks[0].text(), Some("a < b and that is all"));
    }

    #[test]
    fn nothing_here_panics_on_anything() {
        for source in [
            "",
            "<",
            "<<<<<",
            "<!--",
            "<![CDATA[",
            "</p></p></blockquote></ul></pre>",
            "<pre>",
            "<script>",
            &"<blockquote>".repeat(10_000),
            &"<ul>".repeat(10_000),
            &"<p>".repeat(10_000),
            &"&".repeat(10_000),
            &"\u{e9}".repeat(10_000),
        ] {
            let _ = parse(source);
        }
    }

    #[test]
    fn a_document_with_no_tags_at_all_is_still_bounded() {
        let document = parse(&"word ".repeat(200_000));
        assert!(document.truncated);
        assert!(document.blocks[0].text().unwrap_or_default().len() <= MAX_BLOCK_TEXT);
    }
}
