[package]
name = "kobo-stream"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
kobo-abi = { path = "../kobo-abi" }
kobo-json = { path = "../kobo-json" }
kobo-net = { path = "../kobo-net" }
vt100 = "0.16"

[lints]
workspace = true
