[package]
name = "kobo-text"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Real type for the Kobo application platform"

[dependencies]
fontdue = "0.9"
kobo-ui = { path = "../kobo-ui" }
unicode-linebreak = "0.1.5"
unicode-segmentation = "1.12"

[dev-dependencies]
kobo-sdk = { path = "../kobo-sdk" }
